import 'package:sketch_flow/app/localization/translation_keys.dart';

const Map<String, String> deDE = {
  TKeys.appTitle: 'SketchFlow',
  TKeys.appTagline: 'Zeichne in Augmented Reality',
  TKeys.loadingYourCanvas: 'Deine Leinwand wird geladen…',

  TKeys.chooseYourLanguage: 'Wähle Deine Sprache',
  TKeys.selectPreferredLanguage: 'Wähle deine bevorzugte Sprache, um fortzufahren',
  TKeys.continueBtn: 'Weiter',

  TKeys.languageNameEnglish: 'Englisch',
  TKeys.languageNameSpanish: 'Spanisch',
  TKeys.languageNameFrench: 'Französisch',
  TKeys.languageNameGerman: 'Deutsch',
  TKeys.languageNameHindi: 'Hindi',
  TKeys.languageNameChinese: 'Chinesisch',

  TKeys.confirmLanguage: 'Sprache Bestätigen',
  TKeys.changeLanguageAnytime: 'Du kannst dies jederzeit in den Einstellungen ändern',
  TKeys.selected: 'Ausgewählt',
  TKeys.changeLanguage: 'Sprache Ändern',
  TKeys.confirmAndContinue: 'Bestätigen und Fortfahren',

  TKeys.onboardSlide1Title: 'Zeichne Alles in AR',
  TKeys.onboardSlide1Desc:
  'Verwandle deine Vorstellungskraft in Realität, indem du direkt mit deiner Kamera in die reale Welt zeichnest',
  TKeys.onboardSlide2Title: 'Präzises Nachzeichnen',
  TKeys.onboardSlide2Desc:
  'Importiere ein beliebiges Foto und zeichne es mit anpassbaren Deckkraft-Hilfslinien für perfekte Linien nach',
  TKeys.onboardSlide3Title: 'Speichere & Teile Deine Kunst',
  TKeys.onboardSlide3Desc:
  'Exportiere fertige Skizzen in deine Galerie und teile deinen kreativen Prozess mit der Welt',
  TKeys.skip: 'Überspringen',
  TKeys.next: 'Weiter',
  TKeys.getStarted: 'Loslegen',

  TKeys.arDrawingApp: 'AR-ZEICHEN-APP',
  TKeys.helloArtist: 'Hallo, Künstler!',
  TKeys.startADrawing: 'ZEICHNUNG STARTEN',
  TKeys.traceAnyPhoto: 'Zeichne jedes Foto aus der Galerie oder Kamera in AR oder auf Papier nach.',
  TKeys.arCamera: 'AR-Kamera',
  TKeys.onPaper: 'Auf Papier',
  TKeys.exploreFeatures: 'Funktionen Entdecken',
  TKeys.sketch: 'Skizze',
  TKeys.categories: 'Kategorien',
  TKeys.gallery: 'Galerie',
  TKeys.seeAll: 'Alle anzeigen',
  TKeys.pickImageToTrace: 'Wähle ein Bild zum Nachzeichnen in AR oder auf Papier',

  TKeys.leavingSoSoon: 'Schon am Gehen?',
  TKeys.missYourCreations: 'Wir werden deine großartigen AR-Kreationen vermissen!',
  TKeys.stayAndKeepDrawing: 'Bleiben und Weiterzeichnen',
  TKeys.leave: 'Verlassen',

  TKeys.learnToDraw: 'Zeichnen Lernen',
  TKeys.stepByStepTutorials: 'Schritt-für-Schritt-Anleitungen zum Nachzeichnen',
  TKeys.arCameraSublabelTutorial: 'Durchlaufe die Anleitung über deine Live-Kamera',
  TKeys.onPaperSublabelTutorial: 'Durchlaufe die Anleitung am Bildschirm und zeichne sie ab',
  TKeys.howDoYouWantToTrace: 'Wie möchtest du dies nachzeichnen?',
  TKeys.stepsCount: 'Schritte',

  TKeys.stepLabel: 'Schritt',
  TKeys.arCameraSublabelStep: 'Diesen Schritt über deine Live-Kamera legen',
  TKeys.onPaperSublabelStep: 'Diesen Schritt am Bildschirm zeigen und abzeichnen',

  // ── Shared difficulty ─────────────────────────────────────────────────
  TKeys.difficultyBeginner: 'Anfänger',
  TKeys.difficultyIntermediate: 'Fortgeschritten',

  // ── Tutorial: draw-a-face ────────────────────────────────────────────────
  TKeys.tutFaceTitle: 'Wie man ein Gesicht zeichnet',
  TKeys.tutFaceDesc: 'Lerne Gesichtsproportionen Schritt für Schritt',
  TKeys.tutFaceStep1Title: 'Das Hilfsoval',
  TKeys.tutFaceStep1Instruction: 'Beginne mit einem einfachen Oval für die Kopfform.',
  TKeys.tutFaceStep2Title: 'Mittellinien',
  TKeys.tutFaceStep2Instruction: 'Füge eine vertikale und horizontale Mittellinie hinzu, um die Gesichtszüge auszurichten.',
  TKeys.tutFaceStep3Title: 'Kiefer und Kinn',
  TKeys.tutFaceStep3Instruction: 'Verfeinere das Oval zu einer Kiefer- und Kinnform.',
  TKeys.tutFaceStep4Title: 'Augenplatzierung',
  TKeys.tutFaceStep4Instruction: 'Markiere die Augenlinie und verteile fünf Augenbreiten darauf.',
  TKeys.tutFaceStep5Title: 'Augen und Augenbrauen',
  TKeys.tutFaceStep5Instruction: 'Zeichne mandelförmige Augen auf der zweiten und vierten Markierung, dann füge Augenbrauen darüber hinzu.',
  TKeys.tutFaceStep6Title: 'Die Nase',
  TKeys.tutFaceStep6Instruction: 'Die Nasenunterkante liegt auf halbem Weg zwischen Augen und Kinn.',
  TKeys.tutFaceStep7Title: 'Der Mund',
  TKeys.tutFaceStep7Instruction: 'Der Mund liegt ein Drittel des Weges von der Nase zum Kinn.',
  TKeys.tutFaceStep8Title: 'Ohren',
  TKeys.tutFaceStep8Instruction: 'Ohren erstrecken sich von der Augenbrauenlinie bis zur Nasenunterkante.',
  TKeys.tutFaceStep9Title: 'Haare',
  TKeys.tutFaceStep9Instruction: 'Schließe mit einem Haaransatz und ein paar Strähnen für Textur ab.',

  // ── Tutorial: draw-a-cat ─────────────────────────────────────────────────
  TKeys.tutCatTitle: 'Wie man ein Katzengesicht zeichnet',
  TKeys.tutCatDesc: 'Von einfachen Formen zu einer vollständigen Katzengesicht-Skizze',
  TKeys.tutCatStep1Title: 'Der Hilfskreis',
  TKeys.tutCatStep1Instruction: 'Beginne mit einem Kreis für den Kopf, dann füge ein Mittelkreuz hinzu, um die Gesichtszüge auszurichten.',
  TKeys.tutCatStep2Title: 'Ohren hinzufügen',
  TKeys.tutCatStep2Instruction: 'Zeichne zwei dreieckige Ohren oben auf dem Kreis, leicht nach außen geneigt.',
  TKeys.tutCatStep3Title: 'Augen und Nase',
  TKeys.tutCatStep3Instruction: 'Platziere mandelförmige Augen auf der Mittellinie, dann eine kleine Dreiecksnase darunter.',
  TKeys.tutCatStep4Title: 'Maul und Schnurrhaare',
  TKeys.tutCatStep4Instruction: 'Vollende das Maul mit einer geschwungenen Linie von der Nase, dann füge Schnurrhaare und Wangenfell hinzu.',

  // ── Tutorial: draw-a-house ───────────────────────────────────────────────
  TKeys.tutHouseTitle: 'Wie man ein Haus zeichnet',
  TKeys.tutHouseDesc: 'Baue ein gemütliches Cottage aus Grundformen',
  TKeys.tutHouseStep1Title: 'Das Grundrechteck',
  TKeys.tutHouseStep1Instruction: 'Beginne mit einem einfachen Rechteck für die Vorderwand und einer Mittellinie für die Symmetrie.',
  TKeys.tutHouseStep2Title: 'Die Dachlinie',
  TKeys.tutHouseStep2Instruction: 'Füge oben ein Spitzdach hinzu, das sich in einem Punkt über der Mittellinie trifft.',
  TKeys.tutHouseStep3Title: 'Tür und Fenster',
  TKeys.tutHouseStep3Instruction: 'Skizziere eine Tür in der Mitte und ein Fenster auf jeder Seite davon.',
  TKeys.tutHouseStep4Title: 'Schornstein hinzufügen',
  TKeys.tutHouseStep4Instruction: 'Zeichne einen rechteckigen Schornstein, der vom hinteren Dachrand aufsteigt.',
  TKeys.tutHouseStep5Title: 'Dachschindeln',
  TKeys.tutHouseStep5Instruction: 'Fülle das Dach mit kurzen überlappenden Schindellinien für Textur.',
  TKeys.tutHouseStep6Title: 'Wandschattierung',
  TKeys.tutHouseStep6Instruction: 'Füge Schraffuren an Wänden und Dach hinzu, um Schatten und Tiefe anzudeuten.',
  TKeys.tutHouseStep7Title: 'Letzte Details',
  TKeys.tutHouseStep7Instruction: 'Schließe mit einem Türknauf, Fensterscheiben und einer Bodenlinie unter dem Haus ab.',

  // ── Tutorial: draw-a-tree ────────────────────────────────────────────────
  TKeys.tutTreeTitle: 'Wie man einen Baum zeichnet',
  TKeys.tutTreeDesc: 'Lasse eine vollständige Eiche aus einem einfachen Hilfsoval wachsen',
  TKeys.tutTreeStep1Title: 'Das Hilfsoval',
  TKeys.tutTreeStep1Instruction: 'Skizziere ein lockeres Oval für die Baumkrone, dann ziehe eine gerade Stammlinie von der Mitte nach unten.',
  TKeys.tutTreeStep2Title: 'Stamm und Äste',
  TKeys.tutTreeStep2Instruction: 'Verdicke den Stamm und teile ihn in einige Hauptäste, die in das Oval hineinreichen.',
  TKeys.tutTreeStep3Title: 'Kronenumriss',
  TKeys.tutTreeStep3Instruction: 'Zeichne einen unebenen, wolkenähnlichen Umriss um das Oval, um den belaubten Kronenrand zu formen.',
  TKeys.tutTreeStep4Title: 'Rinde und Wurzeln',
  TKeys.tutTreeStep4Instruction: 'Füge Texturlinien am Stamm hinzu und einige sich an der Basis ausbreitende Wurzellinien.',
  TKeys.tutTreeStep5Title: 'Blattbüschel',
  TKeys.tutTreeStep5Instruction: 'Verteile kleine, gezackte Blattbüschel innerhalb der Krone, entlang der Astlinien.',
  TKeys.tutTreeStep6Title: 'Schattierung',
  TKeys.tutTreeStep6Instruction: 'Schattiere die Unterseite der Krone und eine Seite des Stamms, um dem Baum Form zu geben.',

  // ── Tutorial: draw-a-hand ────────────────────────────────────────────────
  TKeys.tutHandTitle: 'Wie man eine Hand zeichnet',
  TKeys.tutHandDesc: 'Zerlege eine erhobene Hand in einfache Formen',
  TKeys.tutHandStep1Title: 'Die Handflächenform',
  TKeys.tutHandStep1Instruction: 'Beginne mit einem abgerundeten Quadrat für die Handfläche, dann füge darunter eine kurze Handgelenklinie hinzu.',
  TKeys.tutHandStep2Title: 'Fingerhilfslinien',
  TKeys.tutHandStep2Instruction: 'Füge fünf gerade Hilfslinien hinzu, die fächerförmig von der Oberseite der Handfläche für jeden Finger ausgehen.',
  TKeys.tutHandStep3Title: 'Fingersegmente',
  TKeys.tutHandStep3Instruction: 'Baue jeden Finger als gestapelte Röhrensegmente entlang seiner Hilfslinie auf, die sich zur Spitze hin leicht verjüngen.',
  TKeys.tutHandStep4Title: 'Umriss verfeinern',
  TKeys.tutHandStep4Instruction: 'Bereinige die äußere Silhouette von Hand und Fingern zu einer durchgehenden Linie.',
  TKeys.tutHandStep5Title: 'Knöchelfalten',
  TKeys.tutHandStep5Instruction: 'Füge kurze geschwungene Falten an jedem Knöchelgelenk hinzu, um zu zeigen, wo sich die Finger biegen.',
  TKeys.tutHandStep6Title: 'Handflächenlinien',
  TKeys.tutHandStep6Instruction: 'Lösche die Konstruktionslinien und füge ein paar sanfte Falten über die Handfläche hinzu.',
  TKeys.tutHandStep7Title: 'Schattierung',
  TKeys.tutHandStep7Instruction: 'Schattiere die Basis der Handfläche und die Seiten der Finger, um der Hand Volumen zu geben.',

  // ── Tutorial: shading-basics ──────────────────────────────────────────────
  TKeys.tutShadingTitle: 'Schattierungsgrundlagen',
  TKeys.tutShadingDesc: 'Licht, Schatten und Form mit einfachen Formen',
  TKeys.tutShadingStep1Title: 'Lichtquelle',
  TKeys.tutShadingStep1Instruction: 'Wähle eine Lichtrichtung und halte sie über die gesamte Zeichnung konsistent.',
  TKeys.tutShadingStep2Title: 'Kernschatten',
  TKeys.tutShadingStep2Instruction: 'Der dunkelste Schatten liegt kurz hinter der Terminatorlinie, nicht direkt am Rand der Form.',

  TKeys.categoriesTitle: 'Kategorien',
  TKeys.categoriesSubtitle: 'Wähle einen Stil, um eine kuratierte Auswahl an Bildern zum Nachzeichnen zu durchsuchen.',
  TKeys.pickImageToTraceArOrPaper: 'Wähle ein Bild zum Nachzeichnen per AR oder auf Papier',

  TKeys.settingsTitle: 'Einstellungen',
  TKeys.sectionDrawing: 'ZEICHNEN',
  TKeys.sectionGeneral: 'ALLGEMEIN',
  TKeys.sectionAboutSupport: 'ÜBER & SUPPORT',

  TKeys.pressureSensitivity: 'Druckempfindlichkeit',
  TKeys.pressureSensitivitySub: 'Für Stifte, die dies unterstützen',
  TKeys.leftHandedMode: 'Linkshänder-Modus',
  TKeys.leftHandedModeSub: 'Werkzeugleiste nach links verschieben',
  TKeys.strokeSmoothing: 'Strichglättung',
  TKeys.hapticFeedback: 'Haptisches Feedback',
  TKeys.autosave: 'Automatisches Speichern',
  TKeys.autosaveSub: 'Änderungen während des Zeichnens speichern',
  TKeys.measurementUnit: 'Maßeinheit',

  TKeys.moreApps: 'Weitere Apps',
  TKeys.shareApp: 'App teilen',
  TKeys.privacyPolicy: 'Datenschutzerklärung',
  TKeys.feedback: 'Feedback',
  TKeys.rateApp: 'App bewerten',
  TKeys.version: 'Version',

  TKeys.choosePhotoToTrace: 'Wähle ein Foto zum Nachzeichnen',
  TKeys.camera: 'Kamera',
  TKeys.opacityLabel: 'Deckkraft',
  TKeys.hideLabel: 'Ausblenden',
  TKeys.extendLabel: 'Erweitern',
  TKeys.lockLabel: 'Sperren',
  TKeys.stepProgress: 'Schritt: @current/@total',

  TKeys.errNoCameraFound: 'Keine Kamera auf diesem Gerät gefunden.',
  TKeys.errCameraStartFailed: 'Kamera konnte nicht gestartet werden. Berechtigungen prüfen.',
  TKeys.errFlashToggleFailed: 'Blitz konnte nicht umgeschaltet werden.',
  TKeys.errFreezeFailed: 'Bild konnte nicht eingefroren werden. Bitte erneut versuchen.',
  TKeys.errImageLoadFailed: 'Dieses Bild konnte nicht geladen werden: @error',
  TKeys.errImageLoadFailedGeneric: 'Dieses Bild konnte nicht geladen werden.',
  TKeys.errImageDisplayFailed: 'Dieses Bild konnte nicht angezeigt werden. Versuche ein anderes Foto.',

  TKeys.nothingToSaveYet: 'Noch nichts zu speichern – diese Skizze ist mit keinem Projekt verknüpft.',
  TKeys.saved: 'Gespeichert',

  TKeys.exportTitle: 'Exportieren',
  TKeys.sectionFormat: 'FORMAT',
  TKeys.sectionResolution: 'AUFLÖSUNG',
  TKeys.flattenLayers: 'Ebenen zusammenführen',
  TKeys.flattenLayersSub: 'Alle sichtbaren Ebenen zu einem Bild zusammenführen',
  TKeys.exportedCheck: 'Exportiert ✓',
  TKeys.exportSketch: 'Skizze exportieren',
  TKeys.errPermissionDenied: 'Die Berechtigung zum Speichern von Fotos wurde verweigert.',
  TKeys.errPsdComingSoon: 'PSD-Export folgt in Kürze.',
  TKeys.errExportFailed: 'Export fehlgeschlagen: @error',

  TKeys.exportFormatPng: 'PNG',
  TKeys.exportFormatJpg: 'JPG',
  TKeys.exportFormatPdf: 'PDF',
  TKeys.exportFormatPsd: 'PSD (demnächst)',

  TKeys.exportResStandard: 'Standard · 1x',
  TKeys.exportResHigh: 'Hoch · 2x',
  TKeys.exportResOriginal: 'Originale Leinwandgröße',

  TKeys.layersTitle: 'Ebenen',
  TKeys.layerOpacityLabel: 'Deckkraft',
  TKeys.blendModeLabel: 'Mischmodus',
  TKeys.duplicate: 'Duplizieren',
  TKeys.delete: 'Löschen',

  TKeys.blendNormal: 'Normal',
  TKeys.blendMultiply: 'Multiplizieren',
  TKeys.blendScreen: 'Negativ multiplizieren',
  TKeys.blendOverlay: 'Ineinanderkopieren',
  TKeys.blendDarken: 'Abdunkeln',
  TKeys.blendLighten: 'Aufhellen',

  TKeys.sketchesTitle: 'Skizzen',
  TKeys.newSketch: 'Neue Skizze',
  TKeys.startYourFirstSketch: 'Starte deine erste Skizze',
  TKeys.sketchesEmptyDesc: 'Zeichnungen, die du mit dem Skizzentool erstellst, erscheinen hier.',

  TKeys.galleryTitle: 'Galerie',
  TKeys.galleryEmptyDesc: 'Gespeicherte Zeichnungen erscheinen hier.',

  TKeys.complementaryLabel: 'Komplementär',
  TKeys.colorHistoryLabel: 'Farbverlauf',
  TKeys.hexPrefix: 'HEX #',
  TKeys.noFavoritesYet: 'Noch keine Favoriten – tippe auf den Stern bei einer Farbe.',
  TKeys.noPalettesYet: 'Noch keine Paletten',
  TKeys.renamePalette: 'Palette umbenennen',
  TKeys.cancel: 'Abbrechen',
  TKeys.save: 'Speichern',
  TKeys.newPalette: 'Neue Palette',

  TKeys.toolsTitle: 'Werkzeuge',
  TKeys.sectionUtility: 'DIENSTPROGRAMME',
  TKeys.sectionBrushSettings: 'PINSELEINSTELLUNGEN',
  TKeys.sizeLabel: 'Größe',
  TKeys.hardnessLabel: 'Härte',

  TKeys.toolPencil: 'Bleistift',
  TKeys.toolPen: 'Stift',
  TKeys.toolMarker: 'Marker',
  TKeys.toolAirbrush: 'Airbrush',
  TKeys.toolSmear: 'Verwischen',
  TKeys.toolEraser: 'Radierer',
  TKeys.toolFill: 'Füllung',
  TKeys.toolEyedropper: 'Pipette',
  TKeys.toolShape: 'Form',
  TKeys.toolText: 'Text',

  TKeys.categoryBasic: 'Basis',
  TKeys.categoryFineArt: 'Bildende Kunst',
  TKeys.categoryMarkers: 'Marker',
  TKeys.categoryArtist: 'Künstler',
  TKeys.categoryPastel: 'Pastell',
  TKeys.categoryTexture: 'Textur',

  TKeys.presetHbPencil: 'HB-Bleistift',
  TKeys.presetFineLiner: 'Fineliner',
  TKeys.presetSoftMarker: 'Weicher Marker',
  TKeys.presetAirbrushSoft: 'Weiches Airbrush',
  TKeys.presetGradePencil: '@grade-Bleistift',
  TKeys.presetChiselMarker: 'Keilspitzen-Marker',
  TKeys.presetBulletMarker: 'Rundspitzen-Marker',
  TKeys.presetBroadMarker: 'Breiter Marker',
  TKeys.presetRoundBrush: 'Rundpinsel',
  TKeys.presetFlatBrush: 'Flachpinsel',
  TKeys.presetFanBrush: 'Fächerpinsel',
  TKeys.presetSoftPastel: 'Weiches Pastell',
  TKeys.presetHardPastel: 'Hartes Pastell',
  TKeys.presetCrosshatch: 'Kreuzschraffur',
  TKeys.presetGrain: 'Körnung',

  TKeys.paletteYellowOrange: 'Gelb und Gelborange',
  TKeys.paletteWarmOranges: 'Warme Orangetöne',
  TKeys.paletteReds: 'Rottöne',
  TKeys.paletteMagenta: 'Magenta',
  TKeys.palettePurples: 'Lilatöne',
  TKeys.paletteBlues: 'Blautöne',
  TKeys.paletteTeals: 'Petroltöne',
  TKeys.paletteGreens: 'Grüntöne',
  TKeys.paletteGreyscale: 'Graustufen',
  TKeys.paletteBrowns: 'Brauntöne',
  TKeys.palettePrimary: 'Primärfarben',

  TKeys.categoryLegacy: 'Klassisch',
  TKeys.categorySynthetic: 'Synthetische Farbe',
  TKeys.categoryTraditional: 'Traditionell',
  TKeys.categoryHalfTone: 'Halbton',
  TKeys.categoryShape: 'Form',
  TKeys.categorySplatter: 'Spritzer',
  TKeys.categoryGlow: 'Leuchten',
  TKeys.categorySmudge: 'Verwischen',
  TKeys.categoryDesigner: 'Designer',
  TKeys.categoryColorless: 'Farblos',

  TKeys.errCouldNotLoadImages: 'Bilder konnten nicht geladen werden: @error',
  TKeys.noImagesYet: 'Noch keine Bilder',
  TKeys.addImagesToFolder: 'Füge Bilder zu @folder/ hinzu und deklariere den Ordner in pubspec.yaml.',
  TKeys.howDoYouWantToTraceThis: 'Wie möchtest du dies nachzeichnen?',
  TKeys.arCameraOption: 'AR-Kamera',
  TKeys.arCameraSublabel: 'Bild über die Live-Kameraansicht legen',
  TKeys.onPaperOption: 'Auf Papier',
  TKeys.onPaperSublabel: 'Bild auf dem Bildschirm anzeigen und von Hand abzeichnen',

  TKeys.drawFromCategory: 'Aus @category zeichnen',
  TKeys.howDoYouWantToTrace2: 'Wie möchtest du nachzeichnen?',
  TKeys.browseCategoryPresets: 'Du kannst @category-Vorlagen durchsuchen, sobald du in einem der beiden Modi bist.',

  TKeys.rename: 'Umbenennen',
  TKeys.exportLabel: 'Exportieren',
  TKeys.renameSketch: 'Skizze umbenennen',
  TKeys.deleteSketchQuestion: 'Skizze löschen?',
  TKeys.deleteSketchConfirm: '„@name" wird endgültig gelöscht.',

  TKeys.catAnime: 'Anime',
  TKeys.catCartoon: 'Cartoon',
  TKeys.catPortrait: 'Porträt',
  TKeys.catAnimals: 'Tiere',
  TKeys.catNature: 'Natur',
  TKeys.catObjects: 'Objekte',

  TKeys.navHome: 'Start',
  TKeys.navLearn: 'Lernen',
  TKeys.navCategories: 'Kategorien',
  TKeys.navSettings: 'Einstellungen',

  TKeys.languageSetting: 'Sprache',
};