import 'package:sketch_flow/app/localization/translation_keys.dart';

const Map<String, String> enUS = {
  TKeys.appTitle: 'SketchFlow',
  TKeys.appTagline: 'Draw in Augmented Reality',
  TKeys.loadingYourCanvas: 'Loading your canvas…',

  TKeys.chooseYourLanguage: 'Choose Your Language',
  TKeys.selectPreferredLanguage: 'Select your preferred language to continue',
  TKeys.continueBtn: 'Continue',

  TKeys.languageNameEnglish: 'English',
  TKeys.languageNameSpanish: 'Spanish',
  TKeys.languageNameFrench: 'French',
  TKeys.languageNameGerman: 'German',
  TKeys.languageNameHindi: 'Hindi',
  TKeys.languageNameChinese: 'Chinese',

  TKeys.confirmLanguage: 'Confirm Language',
  TKeys.changeLanguageAnytime: 'You can change this anytime in settings',
  TKeys.selected: 'Selected',
  TKeys.changeLanguage: 'Change Language',
  TKeys.confirmAndContinue: 'Confirm & Continue',

  TKeys.onboardSlide1Title: 'Draw Anything in AR',
  TKeys.onboardSlide1Desc: 'Turn your imagination into reality by sketching directly onto the real world using your camera',
  TKeys.onboardSlide2Title: 'Trace With Precision',
  TKeys.onboardSlide2Desc: 'Import any photo and trace over it with adjustable opacity guides for perfect line work',
  TKeys.onboardSlide3Title: 'Save & Share Your Art',
  TKeys.onboardSlide3Desc: 'Export finished sketches to your gallery and share your creative process with the world',
  TKeys.skip: 'Skip',
  TKeys.next: 'Next',
  TKeys.getStarted: 'Get Started',

  TKeys.arDrawingApp: 'AR DRAWING APP',
  TKeys.helloArtist: 'Hello, Artist!',
  TKeys.startADrawing: 'START A DRAWING',
  TKeys.traceAnyPhoto: 'Trace any photo from gallery or camera in AR or on paper.',
  TKeys.arCamera: 'AR camera',
  TKeys.onPaper: 'On paper',
  TKeys.exploreFeatures: 'Explore Features',
  TKeys.sketch: 'Sketch',
  TKeys.categories: 'Categories',
  TKeys.gallery: 'Gallery',
  TKeys.seeAll: 'See all',
  TKeys.pickImageToTrace: 'Pick an image to trace with AR or on paper',

  TKeys.leavingSoSoon: 'Leaving So Soon?',
  TKeys.missYourCreations: 'We\'ll miss your amazing AR creations!',
  TKeys.stayAndKeepDrawing: 'Stay & Keep Drawing',
  TKeys.leave: 'Leave',

  TKeys.learnToDraw: 'Learn to Draw',
  TKeys.stepByStepTutorials: 'Step-by-step tutorials you can trace as you go',
  TKeys.arCameraSublabelTutorial: 'Step through the tutorial over your live camera view',
  TKeys.onPaperSublabelTutorial: 'Step through the tutorial on screen and copy by eye',
  TKeys.howDoYouWantToTrace: 'How do you want to trace this?',
  TKeys.stepsCount: 'steps',

  TKeys.stepLabel: 'Step',
  TKeys.arCameraSublabelStep: 'Overlay this step on your live camera view',
  TKeys.onPaperSublabelStep: 'Show this step on screen and copy it by eye',

  // ── Shared difficulty ─────────────────────────────────────────────────
  TKeys.difficultyBeginner: 'Beginner',
  TKeys.difficultyIntermediate: 'Intermediate',

  // ── Tutorial: draw-a-face ────────────────────────────────────────────────
  TKeys.tutFaceTitle: 'How to Draw a Face',
  TKeys.tutFaceDesc: 'Learn face proportions step by step',
  TKeys.tutFaceStep1Title: 'The guide oval',
  TKeys.tutFaceStep1Instruction: 'Start with a simple oval for the head shape.',
  TKeys.tutFaceStep2Title: 'Center lines',
  TKeys.tutFaceStep2Instruction: 'Add a vertical and horizontal center line to line up features.',
  TKeys.tutFaceStep3Title: 'Jaw and chin',
  TKeys.tutFaceStep3Instruction: 'Refine the oval into a jaw and chin shape.',
  TKeys.tutFaceStep4Title: 'Eye placement',
  TKeys.tutFaceStep4Instruction: 'Mark the eye line and space out five eye-widths across it.',
  TKeys.tutFaceStep5Title: 'Eyes and eyebrows',
  TKeys.tutFaceStep5Instruction: 'Draw almond-shaped eyes on the second and fourth marks, then add eyebrows above.',
  TKeys.tutFaceStep6Title: 'The nose',
  TKeys.tutFaceStep6Instruction: 'The nose bottom sits halfway between the eyes and chin.',
  TKeys.tutFaceStep7Title: 'The mouth',
  TKeys.tutFaceStep7Instruction: 'The mouth sits a third of the way down from the nose to the chin.',
  TKeys.tutFaceStep8Title: 'Ears',
  TKeys.tutFaceStep8Instruction: 'Ears span from the eyebrow line down to the bottom of the nose.',
  TKeys.tutFaceStep9Title: 'Hair',
  TKeys.tutFaceStep9Instruction: 'Finish with a hairline and a few strands for texture.',

  // ── Tutorial: draw-a-cat ─────────────────────────────────────────────────
  TKeys.tutCatTitle: 'How to Draw a Cat Face',
  TKeys.tutCatDesc: 'Simple shapes to a full cat face sketch',
  TKeys.tutCatStep1Title: 'The guide circle',
  TKeys.tutCatStep1Instruction: 'Start with a circle for the head, then add a center cross to line up features.',
  TKeys.tutCatStep2Title: 'Add the ears',
  TKeys.tutCatStep2Instruction: 'Draw two triangular ears sitting on top of the circle, slightly angled outward.',
  TKeys.tutCatStep3Title: 'Eyes and nose',
  TKeys.tutCatStep3Instruction: 'Place almond-shaped eyes on the center line, then a small triangle nose below.',
  TKeys.tutCatStep4Title: 'Mouth and whiskers',
  TKeys.tutCatStep4Instruction: 'Finish the mouth with a curved line from the nose, then add whiskers and cheek fur.',

  // ── Tutorial: draw-a-house ───────────────────────────────────────────────
  TKeys.tutHouseTitle: 'How to Draw a House',
  TKeys.tutHouseDesc: 'Build a cozy cottage from basic shapes',
  TKeys.tutHouseStep1Title: 'The base rectangle',
  TKeys.tutHouseStep1Instruction: 'Start with a simple rectangle for the front wall, and a center line to keep things symmetrical.',
  TKeys.tutHouseStep2Title: 'The roofline',
  TKeys.tutHouseStep2Instruction: 'Add a peaked roof on top, meeting at a point above the center line.',
  TKeys.tutHouseStep3Title: 'Door and windows',
  TKeys.tutHouseStep3Instruction: 'Sketch a door in the middle and a window on each side of it.',
  TKeys.tutHouseStep4Title: 'Add the chimney',
  TKeys.tutHouseStep4Instruction: 'Draw a rectangular chimney rising from the back edge of the roof.',
  TKeys.tutHouseStep5Title: 'Roof shingles',
  TKeys.tutHouseStep5Instruction: 'Fill the roof with short overlapping shingle lines for texture.',
  TKeys.tutHouseStep6Title: 'Shading the walls',
  TKeys.tutHouseStep6Instruction: 'Add crosshatching to the walls and roof to suggest shadow and depth.',
  TKeys.tutHouseStep7Title: 'Final details',
  TKeys.tutHouseStep7Instruction: 'Finish with a doorknob, window panes, and a ground line beneath the house.',

  // ── Tutorial: draw-a-tree ────────────────────────────────────────────────
  TKeys.tutTreeTitle: 'How to Draw a Tree',
  TKeys.tutTreeDesc: 'Grow a full oak from a simple oval guide',
  TKeys.tutTreeStep1Title: 'The guide oval',
  TKeys.tutTreeStep1Instruction: 'Sketch a loose oval for the canopy, then drop a trunk line straight down from its center.',
  TKeys.tutTreeStep2Title: 'Trunk and branches',
  TKeys.tutTreeStep2Instruction: 'Thicken the trunk and split it into a few main branches reaching up into the oval.',
  TKeys.tutTreeStep3Title: 'Canopy outline',
  TKeys.tutTreeStep3Instruction: 'Trace a bumpy, cloud-like outline around the oval to form the leafy canopy edge.',
  TKeys.tutTreeStep4Title: 'Bark and roots',
  TKeys.tutTreeStep4Instruction: 'Add texture lines down the trunk and a few root lines flaring out at the base.',
  TKeys.tutTreeStep5Title: 'Leaf clusters',
  TKeys.tutTreeStep5Instruction: 'Scatter small scalloped leaf clusters inside the canopy, following the branch lines.',
  TKeys.tutTreeStep6Title: 'Shading',
  TKeys.tutTreeStep6Instruction: 'Shade the underside of the canopy and one side of the trunk to give the tree form.',

  // ── Tutorial: draw-a-hand ────────────────────────────────────────────────
  TKeys.tutHandTitle: 'How to Draw a Hand',
  TKeys.tutHandDesc: 'Break a raised hand down into simple shapes',
  TKeys.tutHandStep1Title: 'The palm shape',
  TKeys.tutHandStep1Instruction: 'Start with a rounded square for the palm, then add a short wrist line below it.',
  TKeys.tutHandStep2Title: 'Finger guide lines',
  TKeys.tutHandStep2Instruction: 'Add five straight guide lines fanning out from the top of the palm for each finger.',
  TKeys.tutHandStep3Title: 'Finger segments',
  TKeys.tutHandStep3Instruction: 'Build each finger as stacked tube segments along its guide line, tapering slightly toward the tip.',
  TKeys.tutHandStep4Title: 'Refine the outline',
  TKeys.tutHandStep4Instruction: 'Clean up the outer silhouette of the hand and fingers into one continuous line.',
  TKeys.tutHandStep5Title: 'Knuckle creases',
  TKeys.tutHandStep5Instruction: 'Add short curved creases at each knuckle joint to show where the fingers bend.',
  TKeys.tutHandStep6Title: 'Palm lines',
  TKeys.tutHandStep6Instruction: 'Erase the construction lines and add a few soft creases across the palm.',
  TKeys.tutHandStep7Title: 'Shading',
  TKeys.tutHandStep7Instruction: 'Shade the base of the palm and the sides of the fingers to give the hand volume.',

  // ── Tutorial: shading-basics ──────────────────────────────────────────────
  TKeys.tutShadingTitle: 'Shading Basics',
  TKeys.tutShadingDesc: 'Light, shadow, and form with simple shapes',
  TKeys.tutShadingStep1Title: 'Light source',
  TKeys.tutShadingStep1Instruction: 'Pick one light direction and keep it consistent across the whole drawing.',
  TKeys.tutShadingStep2Title: 'Core shadow',
  TKeys.tutShadingStep2Instruction: 'The darkest shadow sits just past the terminator line, not at the very edge of the form.',

  TKeys.categoriesTitle: 'Categories',
  TKeys.categoriesSubtitle: 'Pick a style to browse a curated set of images to trace.',
  TKeys.pickImageToTraceArOrPaper: 'Pick an image to trace with AR or on paper',

  TKeys.settingsTitle: 'Settings',
  TKeys.sectionDrawing: 'DRAWING',
  TKeys.sectionGeneral: 'GENERAL',
  TKeys.sectionAboutSupport: 'ABOUT & SUPPORT',

  TKeys.pressureSensitivity: 'Pressure sensitivity',
  TKeys.pressureSensitivitySub: 'For styluses that support it',
  TKeys.leftHandedMode: 'Left-handed mode',
  TKeys.leftHandedModeSub: 'Move tool dock to the left',
  TKeys.strokeSmoothing: 'Stroke smoothing',
  TKeys.hapticFeedback: 'Haptic feedback',
  TKeys.autosave: 'Autosave',
  TKeys.autosaveSub: 'Save changes as you draw',
  TKeys.measurementUnit: 'Measurement unit',

  TKeys.moreApps: 'More Apps',
  TKeys.shareApp: 'Share App',
  TKeys.privacyPolicy: 'Privacy Policy',
  TKeys.feedback: 'Feedback',
  TKeys.rateApp: 'Rate App',
  TKeys.version: 'Version',

  TKeys.choosePhotoToTrace: 'Choose a photo to trace',
  TKeys.camera: 'Camera',
  TKeys.opacityLabel: 'Opacity',
  TKeys.hideLabel: 'Hide',
  TKeys.extendLabel: 'Extend',
  TKeys.lockLabel: 'Lock',
  TKeys.stepProgress: 'Step: @current/@total',

  TKeys.errNoCameraFound: 'No camera found on this device.',
  TKeys.errCameraStartFailed: 'Could not start the camera. Check permissions.',
  TKeys.errFlashToggleFailed: 'Could not toggle flash.',
  TKeys.errFreezeFailed: 'Could not freeze the frame. Try again.',
  TKeys.errImageLoadFailed: 'Could not load this image: @error',
  TKeys.errImageLoadFailedGeneric: 'Could not load this image.',
  TKeys.errImageDisplayFailed: 'This image could not be displayed. Try a different photo.',

  TKeys.nothingToSaveYet: 'Nothing to save yet — this sketch isn\'t linked to a project.',
  TKeys.saved: 'Saved',

  TKeys.exportTitle: 'Export',
  TKeys.sectionFormat: 'FORMAT',
  TKeys.sectionResolution: 'RESOLUTION',
  TKeys.flattenLayers: 'Flatten layers',
  TKeys.flattenLayersSub: 'Combine all visible layers into one image',
  TKeys.exportedCheck: 'Exported ✓',
  TKeys.exportSketch: 'Export sketch',
  TKeys.errPermissionDenied: 'Permission to save photos was denied.',
  TKeys.errPsdComingSoon: 'PSD export is coming soon.',
  TKeys.errExportFailed: 'Export failed: @error',

  TKeys.exportFormatPng: 'PNG',
  TKeys.exportFormatJpg: 'JPG',
  TKeys.exportFormatPdf: 'PDF',
  TKeys.exportFormatPsd: 'PSD (coming soon)',

  TKeys.exportResStandard: 'Standard · 1x',
  TKeys.exportResHigh: 'High · 2x',
  TKeys.exportResOriginal: 'Original canvas size',

  TKeys.layersTitle: 'Layers',
  TKeys.layerOpacityLabel: 'Opacity',
  TKeys.blendModeLabel: 'Blend mode',
  TKeys.duplicate: 'Duplicate',
  TKeys.delete: 'Delete',

  TKeys.blendNormal: 'Normal',
  TKeys.blendMultiply: 'Multiply',
  TKeys.blendScreen: 'Screen',
  TKeys.blendOverlay: 'Overlay',
  TKeys.blendDarken: 'Darken',
  TKeys.blendLighten: 'Lighten',

  TKeys.sketchesTitle: 'Sketches',
  TKeys.newSketch: 'New sketch',
  TKeys.startYourFirstSketch: 'Start your first sketch',
  TKeys.sketchesEmptyDesc: 'Drawings you make with the sketch tool show up here.',

  TKeys.galleryTitle: 'Gallery',
  TKeys.galleryEmptyDesc: 'Drawings you save will show up here.',

  TKeys.complementaryLabel: 'Complementary',
  TKeys.colorHistoryLabel: 'Color History',
  TKeys.hexPrefix: 'HEX #',
  TKeys.noFavoritesYet: 'No favorites yet — tap the star on any color.',
  TKeys.noPalettesYet: 'No palettes yet',
  TKeys.renamePalette: 'Rename palette',
  TKeys.cancel: 'Cancel',
  TKeys.save: 'Save',
  TKeys.newPalette: 'New Palette',

  TKeys.toolsTitle: 'Tools',
  TKeys.sectionUtility: 'UTILITY',
  TKeys.sectionBrushSettings: 'BRUSH SETTINGS',
  TKeys.sizeLabel: 'Size',
  TKeys.hardnessLabel: 'Hardness',

  TKeys.toolPencil: 'Pencil',
  TKeys.toolPen: 'Pen',
  TKeys.toolMarker: 'Marker',
  TKeys.toolAirbrush: 'Airbrush',
  TKeys.toolSmear: 'Smear',
  TKeys.toolEraser: 'Eraser',
  TKeys.toolFill: 'Fill',
  TKeys.toolEyedropper: 'Eyedropper',
  TKeys.toolShape: 'Shape',
  TKeys.toolText: 'Text',

  TKeys.categoryBasic: 'Basic',
  TKeys.categoryFineArt: 'Fine Art',
  TKeys.categoryMarkers: 'Markers',
  TKeys.categoryArtist: 'Artist',
  TKeys.categoryPastel: 'Pastel',
  TKeys.categoryTexture: 'Texture',

  TKeys.presetHbPencil: 'HB Pencil',
  TKeys.presetFineLiner: 'Fine Liner',
  TKeys.presetSoftMarker: 'Soft Marker',
  TKeys.presetAirbrushSoft: 'Airbrush Soft',
  TKeys.presetGradePencil: '@grade Pencil',
  TKeys.presetChiselMarker: 'Chisel Marker',
  TKeys.presetBulletMarker: 'Bullet Marker',
  TKeys.presetBroadMarker: 'Broad Marker',
  TKeys.presetRoundBrush: 'Round Brush',
  TKeys.presetFlatBrush: 'Flat Brush',
  TKeys.presetFanBrush: 'Fan Brush',
  TKeys.presetSoftPastel: 'Soft Pastel',
  TKeys.presetHardPastel: 'Hard Pastel',
  TKeys.presetCrosshatch: 'Crosshatch',
  TKeys.presetGrain: 'Grain',

  TKeys.paletteYellowOrange: 'Yellow and Yellow Orange',
  TKeys.paletteWarmOranges: 'Warm Oranges',
  TKeys.paletteReds: 'Reds',
  TKeys.paletteMagenta: 'Magenta',
  TKeys.palettePurples: 'Purples',
  TKeys.paletteBlues: 'Blues',
  TKeys.paletteTeals: 'Teals',
  TKeys.paletteGreens: 'Greens',
  TKeys.paletteGreyscale: 'Greyscale',
  TKeys.paletteBrowns: 'Browns',
  TKeys.palettePrimary: 'Primary',

  TKeys.categoryLegacy: 'Legacy',
  TKeys.categorySynthetic: 'Synthetic Paint',
  TKeys.categoryTraditional: 'Traditional',
  TKeys.categoryHalfTone: 'Half Tone',
  TKeys.categoryShape: 'Shape',
  TKeys.categorySplatter: 'Splatter',
  TKeys.categoryGlow: 'Glow',
  TKeys.categorySmudge: 'Smudge',
  TKeys.categoryDesigner: 'Designer',
  TKeys.categoryColorless: 'Colorless',

  TKeys.errCouldNotLoadImages: 'Could not load images: @error',
  TKeys.noImagesYet: 'No images yet',
  TKeys.addImagesToFolder: 'Add images to @folder/ and declare the folder in pubspec.yaml.',
  TKeys.howDoYouWantToTraceThis: 'How do you want to trace this?',
  TKeys.arCameraOption: 'AR camera',
  TKeys.arCameraSublabel: 'Overlay the image on your live camera view',
  TKeys.onPaperOption: 'On paper',
  TKeys.onPaperSublabel: 'Show the image on screen and copy it by eye',

  TKeys.drawFromCategory: 'Draw from @category',
  TKeys.howDoYouWantToTrace2: 'How do you want to trace?',
  TKeys.browseCategoryPresets: 'You can browse @category presets once you\'re in either mode.',

  TKeys.rename: 'Rename',
  TKeys.exportLabel: 'Export',
  TKeys.renameSketch: 'Rename sketch',
  TKeys.deleteSketchQuestion: 'Delete sketch?',
  TKeys.deleteSketchConfirm: '"@name" will be permanently deleted.',

  TKeys.catAnime: 'Anime',
  TKeys.catCartoon: 'Cartoon',
  TKeys.catPortrait: 'Portrait',
  TKeys.catAnimals: 'Animals',
  TKeys.catNature: 'Nature',
  TKeys.catObjects: 'Objects',

  TKeys.navHome: 'Home',
  TKeys.navLearn: 'Learn',
  TKeys.navCategories: 'Categories',
  TKeys.navSettings: 'Settings',

  TKeys.languageSetting: 'Language',

  TKeys.preparingYourExperience: 'Just a moment...',
  TKeys.errCameraPermissionDenied: 'Camera permission denied',
  TKeys.errGalleryPermissionDenied: 'Gallery permission denied',

  TKeys.notifications: 'Notifications',
  TKeys.notificationsEnabledSub: 'You will receive updates and reminders',
  TKeys.notificationsDisabledSub: 'Tap to enable in system settings',
};