import 'package:sketch_flow/app/localization/translation_keys.dart';

const Map<String, String> esES = {
  TKeys.appTitle: 'SketchFlow',
  TKeys.appTagline: 'Dibuja en Realidad Aumentada',
  TKeys.loadingYourCanvas: 'Cargando tu lienzo…',

  TKeys.chooseYourLanguage: 'Elige Tu Idioma',
  TKeys.selectPreferredLanguage: 'Selecciona tu idioma preferido para continuar',
  TKeys.continueBtn: 'Continuar',

  TKeys.languageNameEnglish: 'Inglés',
  TKeys.languageNameSpanish: 'Español',
  TKeys.languageNameFrench: 'Francés',
  TKeys.languageNameGerman: 'Alemán',
  TKeys.languageNameHindi: 'Hindi',
  TKeys.languageNameChinese: 'Chino',

  TKeys.confirmLanguage: 'Confirmar Idioma',
  TKeys.changeLanguageAnytime: 'Puedes cambiar esto en cualquier momento en ajustes',
  TKeys.selected: 'Seleccionado',
  TKeys.changeLanguage: 'Cambiar Idioma',
  TKeys.confirmAndContinue: 'Confirmar y Continuar',

  TKeys.onboardSlide1Title: 'Dibuja Cualquier Cosa en RA',
  TKeys.onboardSlide1Desc:
  'Convierte tu imaginación en realidad dibujando directamente sobre el mundo real usando tu cámara',
  TKeys.onboardSlide2Title: 'Calca con Precisión',
  TKeys.onboardSlide2Desc:
  'Importa cualquier foto y calca sobre ella con guías de opacidad ajustables para un trazo perfecto',
  TKeys.onboardSlide3Title: 'Guarda y Comparte tu Arte',
  TKeys.onboardSlide3Desc:
  'Exporta tus bocetos terminados a tu galería y comparte tu proceso creativo con el mundo',
  TKeys.skip: 'Omitir',
  TKeys.next: 'Siguiente',
  TKeys.getStarted: 'Comenzar',

  TKeys.arDrawingApp: 'APLICACIÓN DE DIBUJO RA',
  TKeys.helloArtist: '¡Hola, Artista!',
  TKeys.startADrawing: 'INICIA UN DIBUJO',
  TKeys.traceAnyPhoto: 'Calca cualquier foto de la galería o cámara en RA o en papel.',
  TKeys.arCamera: 'Cámara RA',
  TKeys.onPaper: 'En papel',
  TKeys.exploreFeatures: 'Explorar Funciones',
  TKeys.sketch: 'Boceto',
  TKeys.categories: 'Categorías',
  TKeys.gallery: 'Galería',
  TKeys.seeAll: 'Ver todo',
  TKeys.pickImageToTrace: 'Elige una imagen para calcar con RA o en papel',

  TKeys.leavingSoSoon: '¿Ya Te Vas?',
  TKeys.missYourCreations: '¡Extrañaremos tus increíbles creaciones en RA!',
  TKeys.stayAndKeepDrawing: 'Quedarme y Seguir Dibujando',
  TKeys.leave: 'Salir',

  TKeys.learnToDraw: 'Aprende a Dibujar',
  TKeys.stepByStepTutorials: 'Tutoriales paso a paso que puedes calcar mientras avanzas',
  TKeys.arCameraSublabelTutorial: 'Recorre el tutorial sobre tu vista de cámara en vivo',
  TKeys.onPaperSublabelTutorial: 'Recorre el tutorial en pantalla y cópialo a mano',
  TKeys.howDoYouWantToTrace: '¿Cómo quieres calcar esto?',
  TKeys.stepsCount: 'pasos',

  TKeys.stepLabel: 'Paso',
  TKeys.arCameraSublabelStep: 'Superpón este paso en tu vista de cámara en vivo',
  TKeys.onPaperSublabelStep: 'Muestra este paso en pantalla y cópialo a mano',

  // ── Shared difficulty ─────────────────────────────────────────────────
  TKeys.difficultyBeginner: 'Principiante',
  TKeys.difficultyIntermediate: 'Intermedio',

  // ── Tutorial: draw-a-face ────────────────────────────────────────────────
  TKeys.tutFaceTitle: 'Cómo Dibujar un Rostro',
  TKeys.tutFaceDesc: 'Aprende las proporciones faciales paso a paso',
  TKeys.tutFaceStep1Title: 'El óvalo guía',
  TKeys.tutFaceStep1Instruction: 'Comienza con un óvalo simple para la forma de la cabeza.',
  TKeys.tutFaceStep2Title: 'Líneas centrales',
  TKeys.tutFaceStep2Instruction: 'Añade una línea central vertical y horizontal para alinear los rasgos.',
  TKeys.tutFaceStep3Title: 'Mandíbula y mentón',
  TKeys.tutFaceStep3Instruction: 'Refina el óvalo en una forma de mandíbula y mentón.',
  TKeys.tutFaceStep4Title: 'Ubicación de los ojos',
  TKeys.tutFaceStep4Instruction: 'Marca la línea de los ojos y distribuye cinco anchos de ojo a lo largo de ella.',
  TKeys.tutFaceStep5Title: 'Ojos y cejas',
  TKeys.tutFaceStep5Instruction: 'Dibuja ojos en forma de almendra en la segunda y cuarta marca, luego añade cejas arriba.',
  TKeys.tutFaceStep6Title: 'La nariz',
  TKeys.tutFaceStep6Instruction: 'La base de la nariz se sitúa a medio camino entre los ojos y el mentón.',
  TKeys.tutFaceStep7Title: 'La boca',
  TKeys.tutFaceStep7Instruction: 'La boca se sitúa a un tercio del camino entre la nariz y el mentón.',
  TKeys.tutFaceStep8Title: 'Orejas',
  TKeys.tutFaceStep8Instruction: 'Las orejas van desde la línea de las cejas hasta la base de la nariz.',
  TKeys.tutFaceStep9Title: 'Cabello',
  TKeys.tutFaceStep9Instruction: 'Termina con la línea del cabello y algunos mechones para dar textura.',

  // ── Tutorial: draw-a-cat ─────────────────────────────────────────────────
  TKeys.tutCatTitle: 'Cómo Dibujar la Cara de un Gato',
  TKeys.tutCatDesc: 'De formas simples a un boceto completo de la cara de un gato',
  TKeys.tutCatStep1Title: 'El círculo guía',
  TKeys.tutCatStep1Instruction: 'Comienza con un círculo para la cabeza, luego añade una cruz central para alinear los rasgos.',
  TKeys.tutCatStep2Title: 'Añade las orejas',
  TKeys.tutCatStep2Instruction: 'Dibuja dos orejas triangulares en la parte superior del círculo, ligeramente inclinadas hacia afuera.',
  TKeys.tutCatStep3Title: 'Ojos y nariz',
  TKeys.tutCatStep3Instruction: 'Coloca ojos en forma de almendra en la línea central, luego una pequeña nariz triangular debajo.',
  TKeys.tutCatStep4Title: 'Boca y bigotes',
  TKeys.tutCatStep4Instruction: 'Termina la boca con una línea curva desde la nariz, luego añade bigotes y pelaje en las mejillas.',

  // ── Tutorial: draw-a-house ───────────────────────────────────────────────
  TKeys.tutHouseTitle: 'Cómo Dibujar una Casa',
  TKeys.tutHouseDesc: 'Construye una acogedora casita a partir de formas básicas',
  TKeys.tutHouseStep1Title: 'El rectángulo base',
  TKeys.tutHouseStep1Instruction: 'Comienza con un rectángulo simple para la pared frontal, y una línea central para mantener la simetría.',
  TKeys.tutHouseStep2Title: 'La línea del tejado',
  TKeys.tutHouseStep2Instruction: 'Añade un tejado a dos aguas encima, que se encuentre en un punto sobre la línea central.',
  TKeys.tutHouseStep3Title: 'Puerta y ventanas',
  TKeys.tutHouseStep3Instruction: 'Dibuja una puerta en el medio y una ventana a cada lado.',
  TKeys.tutHouseStep4Title: 'Añade la chimenea',
  TKeys.tutHouseStep4Instruction: 'Dibuja una chimenea rectangular que se eleva desde el borde trasero del tejado.',
  TKeys.tutHouseStep5Title: 'Tejas del tejado',
  TKeys.tutHouseStep5Instruction: 'Rellena el tejado con líneas cortas superpuestas que simulen tejas, para dar textura.',
  TKeys.tutHouseStep6Title: 'Sombreado de las paredes',
  TKeys.tutHouseStep6Instruction: 'Añade un entramado a las paredes y el tejado para sugerir sombra y profundidad.',
  TKeys.tutHouseStep7Title: 'Detalles finales',
  TKeys.tutHouseStep7Instruction: 'Termina con un pomo, los paneles de las ventanas y una línea de suelo debajo de la casa.',

  // ── Tutorial: draw-a-tree ────────────────────────────────────────────────
  TKeys.tutTreeTitle: 'Cómo Dibujar un Árbol',
  TKeys.tutTreeDesc: 'Haz crecer un roble completo a partir de un óvalo guía simple',
  TKeys.tutTreeStep1Title: 'El óvalo guía',
  TKeys.tutTreeStep1Instruction: 'Dibuja un óvalo suelto para la copa, luego traza una línea de tronco recta hacia abajo desde su centro.',
  TKeys.tutTreeStep2Title: 'Tronco y ramas',
  TKeys.tutTreeStep2Instruction: 'Engrosa el tronco y divídelo en algunas ramas principales que se extiendan hacia el óvalo.',
  TKeys.tutTreeStep3Title: 'Contorno de la copa',
  TKeys.tutTreeStep3Instruction: 'Traza un contorno irregular, como una nube, alrededor del óvalo para formar el borde frondoso de la copa.',
  TKeys.tutTreeStep4Title: 'Corteza y raíces',
  TKeys.tutTreeStep4Instruction: 'Añade líneas de textura a lo largo del tronco y algunas líneas de raíces que se ensanchen en la base.',
  TKeys.tutTreeStep5Title: 'Racimos de hojas',
  TKeys.tutTreeStep5Instruction: 'Esparce pequeños racimos de hojas festoneadas dentro de la copa, siguiendo las líneas de las ramas.',
  TKeys.tutTreeStep6Title: 'Sombreado',
  TKeys.tutTreeStep6Instruction: 'Sombrea la parte inferior de la copa y un lado del tronco para dar volumen al árbol.',

  // ── Tutorial: draw-a-hand ────────────────────────────────────────────────
  TKeys.tutHandTitle: 'Cómo Dibujar una Mano',
  TKeys.tutHandDesc: 'Descompón una mano levantada en formas simples',
  TKeys.tutHandStep1Title: 'La forma de la palma',
  TKeys.tutHandStep1Instruction: 'Comienza con un cuadrado redondeado para la palma, luego añade una línea corta de muñeca debajo.',
  TKeys.tutHandStep2Title: 'Líneas guía de los dedos',
  TKeys.tutHandStep2Instruction: 'Añade cinco líneas guía rectas que se abran en abanico desde la parte superior de la palma para cada dedo.',
  TKeys.tutHandStep3Title: 'Segmentos de los dedos',
  TKeys.tutHandStep3Instruction: 'Construye cada dedo como segmentos de tubo apilados a lo largo de su línea guía, estrechándose ligeramente hacia la punta.',
  TKeys.tutHandStep4Title: 'Refina el contorno',
  TKeys.tutHandStep4Instruction: 'Limpia la silueta exterior de la mano y los dedos en una sola línea continua.',
  TKeys.tutHandStep5Title: 'Pliegues de los nudillos',
  TKeys.tutHandStep5Instruction: 'Añade pequeños pliegues curvos en cada articulación de los nudillos para mostrar dónde se doblan los dedos.',
  TKeys.tutHandStep6Title: 'Líneas de la palma',
  TKeys.tutHandStep6Instruction: 'Borra las líneas de construcción y añade algunos pliegues suaves a lo largo de la palma.',
  TKeys.tutHandStep7Title: 'Sombreado',
  TKeys.tutHandStep7Instruction: 'Sombrea la base de la palma y los lados de los dedos para dar volumen a la mano.',

  // ── Tutorial: shading-basics ──────────────────────────────────────────────
  TKeys.tutShadingTitle: 'Fundamentos del Sombreado',
  TKeys.tutShadingDesc: 'Luz, sombra y forma con figuras simples',
  TKeys.tutShadingStep1Title: 'Fuente de luz',
  TKeys.tutShadingStep1Instruction: 'Elige una dirección de luz y mantenla consistente en todo el dibujo.',
  TKeys.tutShadingStep2Title: 'Sombra central',
  TKeys.tutShadingStep2Instruction: 'La sombra más oscura se sitúa justo después de la línea terminadora, no en el borde mismo de la forma.',

  TKeys.categoriesTitle: 'Categorías',
  TKeys.categoriesSubtitle: 'Elige un estilo para explorar una selección de imágenes para calcar.',
  TKeys.pickImageToTraceArOrPaper: 'Elige una imagen para calcar con RA o en papel',

  TKeys.settingsTitle: 'Ajustes',
  TKeys.sectionDrawing: 'DIBUJO',
  TKeys.sectionGeneral: 'GENERAL',
  TKeys.sectionAboutSupport: 'ACERCA DE Y SOPORTE',

  TKeys.pressureSensitivity: 'Sensibilidad a la presión',
  TKeys.pressureSensitivitySub: 'Para lápices ópticos compatibles',
  TKeys.leftHandedMode: 'Modo para zurdos',
  TKeys.leftHandedModeSub: 'Mover la barra de herramientas a la izquierda',
  TKeys.strokeSmoothing: 'Suavizado de trazo',
  TKeys.hapticFeedback: 'Vibración táctil',
  TKeys.autosave: 'Guardado automático',
  TKeys.autosaveSub: 'Guardar cambios mientras dibujas',
  TKeys.measurementUnit: 'Unidad de medida',

  TKeys.moreApps: 'Más aplicaciones',
  TKeys.shareApp: 'Compartir app',
  TKeys.privacyPolicy: 'Política de privacidad',
  TKeys.feedback: 'Comentarios',
  TKeys.rateApp: 'Calificar app',
  TKeys.version: 'Versión',

  TKeys.choosePhotoToTrace: 'Elige una foto para calcar',
  TKeys.camera: 'Cámara',
  TKeys.opacityLabel: 'Opacidad',
  TKeys.hideLabel: 'Ocultar',
  TKeys.extendLabel: 'Ampliar',
  TKeys.lockLabel: 'Bloquear',
  TKeys.stepProgress: 'Paso: @current/@total',

  TKeys.errNoCameraFound: 'No se encontró ninguna cámara en este dispositivo.',
  TKeys.errCameraStartFailed: 'No se pudo iniciar la cámara. Revisa los permisos.',
  TKeys.errFlashToggleFailed: 'No se pudo cambiar el flash.',
  TKeys.errFreezeFailed: 'No se pudo congelar la imagen. Inténtalo de nuevo.',
  TKeys.errImageLoadFailed: 'No se pudo cargar esta imagen: @error',
  TKeys.errImageLoadFailedGeneric: 'No se pudo cargar esta imagen.',
  TKeys.errImageDisplayFailed: 'No se pudo mostrar esta imagen. Prueba con otra foto.',

  TKeys.nothingToSaveYet: 'Aún no hay nada que guardar: este boceto no está vinculado a un proyecto.',
  TKeys.saved: 'Guardado',

  TKeys.exportTitle: 'Exportar',
  TKeys.sectionFormat: 'FORMATO',
  TKeys.sectionResolution: 'RESOLUCIÓN',
  TKeys.flattenLayers: 'Aplanar capas',
  TKeys.flattenLayersSub: 'Combinar todas las capas visibles en una sola imagen',
  TKeys.exportedCheck: 'Exportado ✓',
  TKeys.exportSketch: 'Exportar boceto',
  TKeys.errPermissionDenied: 'Se denegó el permiso para guardar fotos.',
  TKeys.errPsdComingSoon: 'La exportación a PSD estará disponible pronto.',
  TKeys.errExportFailed: 'Error al exportar: @error',

  TKeys.exportFormatPng: 'PNG',
  TKeys.exportFormatJpg: 'JPG',
  TKeys.exportFormatPdf: 'PDF',
  TKeys.exportFormatPsd: 'PSD (próximamente)',

  TKeys.exportResStandard: 'Estándar · 1x',
  TKeys.exportResHigh: 'Alta · 2x',
  TKeys.exportResOriginal: 'Tamaño de lienzo original',

  TKeys.layersTitle: 'Capas',
  TKeys.layerOpacityLabel: 'Opacidad',
  TKeys.blendModeLabel: 'Modo de fusión',
  TKeys.duplicate: 'Duplicar',
  TKeys.delete: 'Eliminar',

  TKeys.blendNormal: 'Normal',
  TKeys.blendMultiply: 'Multiplicar',
  TKeys.blendScreen: 'Trama',
  TKeys.blendOverlay: 'Superponer',
  TKeys.blendDarken: 'Oscurecer',
  TKeys.blendLighten: 'Aclarar',

  TKeys.sketchesTitle: 'Bocetos',
  TKeys.newSketch: 'Nuevo boceto',
  TKeys.startYourFirstSketch: 'Comienza tu primer boceto',
  TKeys.sketchesEmptyDesc: 'Los dibujos que hagas con la herramienta de boceto aparecerán aquí.',

  TKeys.galleryTitle: 'Galería',
  TKeys.galleryEmptyDesc: 'Los dibujos que guardes aparecerán aquí.',

  TKeys.complementaryLabel: 'Complementario',
  TKeys.colorHistoryLabel: 'Historial de colores',
  TKeys.hexPrefix: 'HEX #',
  TKeys.noFavoritesYet: 'Aún no hay favoritos: toca la estrella en cualquier color.',
  TKeys.noPalettesYet: 'Aún no hay paletas',
  TKeys.renamePalette: 'Renombrar paleta',
  TKeys.cancel: 'Cancelar',
  TKeys.save: 'Guardar',
  TKeys.newPalette: 'Nueva paleta',

  TKeys.toolsTitle: 'Herramientas',
  TKeys.sectionUtility: 'UTILIDAD',
  TKeys.sectionBrushSettings: 'AJUSTES DE PINCEL',
  TKeys.sizeLabel: 'Tamaño',
  TKeys.hardnessLabel: 'Dureza',

  TKeys.toolPencil: 'Lápiz',
  TKeys.toolPen: 'Pluma',
  TKeys.toolMarker: 'Marcador',
  TKeys.toolAirbrush: 'Aerógrafo',
  TKeys.toolSmear: 'Difuminar',
  TKeys.toolEraser: 'Borrador',
  TKeys.toolFill: 'Relleno',
  TKeys.toolEyedropper: 'Cuentagotas',
  TKeys.toolShape: 'Forma',
  TKeys.toolText: 'Texto',

  TKeys.categoryBasic: 'Básico',
  TKeys.categoryFineArt: 'Bellas Artes',
  TKeys.categoryMarkers: 'Marcadores',
  TKeys.categoryArtist: 'Artista',
  TKeys.categoryPastel: 'Pastel',
  TKeys.categoryTexture: 'Textura',

  TKeys.presetHbPencil: 'Lápiz HB',
  TKeys.presetFineLiner: 'Rotulador fino',
  TKeys.presetSoftMarker: 'Marcador suave',
  TKeys.presetAirbrushSoft: 'Aerógrafo suave',
  TKeys.presetGradePencil: 'Lápiz @grade',
  TKeys.presetChiselMarker: 'Marcador biselado',
  TKeys.presetBulletMarker: 'Marcador de punta redonda',
  TKeys.presetBroadMarker: 'Marcador ancho',
  TKeys.presetRoundBrush: 'Pincel redondo',
  TKeys.presetFlatBrush: 'Pincel plano',
  TKeys.presetFanBrush: 'Pincel de abanico',
  TKeys.presetSoftPastel: 'Pastel suave',
  TKeys.presetHardPastel: 'Pastel duro',
  TKeys.presetCrosshatch: 'Trama cruzada',
  TKeys.presetGrain: 'Grano',

  TKeys.paletteYellowOrange: 'Amarillo y naranja amarillento',
  TKeys.paletteWarmOranges: 'Naranjas cálidos',
  TKeys.paletteReds: 'Rojos',
  TKeys.paletteMagenta: 'Magenta',
  TKeys.palettePurples: 'Morados',
  TKeys.paletteBlues: 'Azules',
  TKeys.paletteTeals: 'Verdes azulados',
  TKeys.paletteGreens: 'Verdes',
  TKeys.paletteGreyscale: 'Escala de grises',
  TKeys.paletteBrowns: 'Marrones',
  TKeys.palettePrimary: 'Primarios',

  TKeys.categoryLegacy: 'Clásico',
  TKeys.categorySynthetic: 'Pintura sintética',
  TKeys.categoryTraditional: 'Tradicional',
  TKeys.categoryHalfTone: 'Medio tono',
  TKeys.categoryShape: 'Forma',
  TKeys.categorySplatter: 'Salpicadura',
  TKeys.categoryGlow: 'Resplandor',
  TKeys.categorySmudge: 'Difuminado',
  TKeys.categoryDesigner: 'Diseñador',
  TKeys.categoryColorless: 'Incoloro',

  TKeys.errCouldNotLoadImages: 'No se pudieron cargar las imágenes: @error',
  TKeys.noImagesYet: 'Aún no hay imágenes',
  TKeys.addImagesToFolder: 'Agrega imágenes a @folder/ y declara la carpeta en pubspec.yaml.',
  TKeys.howDoYouWantToTraceThis: '¿Cómo quieres calcar esto?',
  TKeys.arCameraOption: 'Cámara RA',
  TKeys.arCameraSublabel: 'Superpón la imagen en tu vista de cámara en vivo',
  TKeys.onPaperOption: 'En papel',
  TKeys.onPaperSublabel: 'Muestra la imagen en pantalla y cópiala a mano',

  TKeys.drawFromCategory: 'Dibujar desde @category',
  TKeys.howDoYouWantToTrace2: '¿Cómo quieres calcar?',
  TKeys.browseCategoryPresets: 'Podrás explorar los ajustes de @category una vez que estés en cualquiera de los dos modos.',

  TKeys.rename: 'Renombrar',
  TKeys.exportLabel: 'Exportar',
  TKeys.renameSketch: 'Renombrar boceto',
  TKeys.deleteSketchQuestion: '¿Eliminar boceto?',
  TKeys.deleteSketchConfirm: '"@name" se eliminará permanentemente.',

  TKeys.catAnime: 'Anime',
  TKeys.catCartoon: 'Dibujos animados',
  TKeys.catPortrait: 'Retrato',
  TKeys.catAnimals: 'Animales',
  TKeys.catNature: 'Naturaleza',
  TKeys.catObjects: 'Objetos',

  TKeys.navHome: 'Inicio',
  TKeys.navLearn: 'Aprender',
  TKeys.navCategories: 'Categorías',
  TKeys.navSettings: 'Ajustes',

  TKeys.languageSetting: 'Idioma',
};