import 'package:sketch_flow/app/localization/translation_keys.dart';

const Map<String, String> frFR = {
  TKeys.appTitle: 'SketchFlow',
  TKeys.appTagline: 'Dessinez en Réalité Augmentée',
  TKeys.loadingYourCanvas: 'Chargement de votre canevas…',

  TKeys.chooseYourLanguage: 'Choisissez Votre Langue',
  TKeys.selectPreferredLanguage: 'Sélectionnez votre langue préférée pour continuer',
  TKeys.continueBtn: 'Continuer',

  TKeys.languageNameEnglish: 'Anglais',
  TKeys.languageNameSpanish: 'Espagnol',
  TKeys.languageNameFrench: 'Français',
  TKeys.languageNameGerman: 'Allemand',
  TKeys.languageNameHindi: 'Hindi',
  TKeys.languageNameChinese: 'Chinois',

  TKeys.confirmLanguage: 'Confirmer la Langue',
  TKeys.changeLanguageAnytime: 'Vous pouvez modifier ceci à tout moment dans les paramètres',
  TKeys.selected: 'Sélectionné',
  TKeys.changeLanguage: 'Changer de Langue',
  TKeys.confirmAndContinue: 'Confirmer et Continuer',

  TKeys.onboardSlide1Title: "Dessinez N'importe Quoi en RA",
  TKeys.onboardSlide1Desc:
  'Transformez votre imagination en réalité en dessinant directement sur le monde réel avec votre caméra',
  TKeys.onboardSlide2Title: 'Calquez avec Précision',
  TKeys.onboardSlide2Desc:
  "Importez n'importe quelle photo et calquez-la avec des guides d'opacité réglables pour un trait parfait",
  TKeys.onboardSlide3Title: 'Enregistrez et Partagez Votre Art',
  TKeys.onboardSlide3Desc:
  'Exportez vos croquis terminés vers votre galerie et partagez votre processus créatif avec le monde',
  TKeys.skip: 'Passer',
  TKeys.next: 'Suivant',
  TKeys.getStarted: 'Commencer',

  TKeys.arDrawingApp: 'APPLI DE DESSIN RA',
  TKeys.helloArtist: 'Bonjour, Artiste !',
  TKeys.startADrawing: 'COMMENCER UN DESSIN',
  TKeys.traceAnyPhoto: 'Calquez n\'importe quelle photo de la galerie ou de la caméra en RA ou sur papier.',
  TKeys.arCamera: 'Caméra RA',
  TKeys.onPaper: 'Sur papier',
  TKeys.exploreFeatures: 'Explorer les Fonctionnalités',
  TKeys.sketch: 'Croquis',
  TKeys.categories: 'Catégories',
  TKeys.gallery: 'Galerie',
  TKeys.seeAll: 'Tout voir',
  TKeys.pickImageToTrace: 'Choisissez une image à calquer en RA ou sur papier',

  TKeys.leavingSoSoon: 'Vous Partez Déjà ?',
  TKeys.missYourCreations: 'Vos superbes créations en RA vont nous manquer !',
  TKeys.stayAndKeepDrawing: 'Rester et Continuer à Dessiner',
  TKeys.leave: 'Quitter',

  TKeys.learnToDraw: 'Apprendre à Dessiner',
  TKeys.stepByStepTutorials: 'Tutoriels étape par étape à calquer au fur et à mesure',
  TKeys.arCameraSublabelTutorial: 'Suivez le tutoriel par-dessus votre caméra en direct',
  TKeys.onPaperSublabelTutorial: 'Suivez le tutoriel à l\'écran et recopiez-le à l\'œil',
  TKeys.howDoYouWantToTrace: 'Comment voulez-vous calquer ceci ?',
  TKeys.stepsCount: 'étapes',

  TKeys.stepLabel: 'Étape',
  TKeys.arCameraSublabelStep: 'Superposez cette étape sur votre caméra en direct',
  TKeys.onPaperSublabelStep: 'Affichez cette étape à l\'écran et recopiez-la à l\'œil',

  // ── Shared difficulty ─────────────────────────────────────────────────
  TKeys.difficultyBeginner: 'Débutant',
  TKeys.difficultyIntermediate: 'Intermédiaire',

  // ── Tutorial: draw-a-face ────────────────────────────────────────────────
  TKeys.tutFaceTitle: 'Comment Dessiner un Visage',
  TKeys.tutFaceDesc: 'Apprenez les proportions du visage étape par étape',
  TKeys.tutFaceStep1Title: "L'ovale guide",
  TKeys.tutFaceStep1Instruction: 'Commencez par un ovale simple pour la forme de la tête.',
  TKeys.tutFaceStep2Title: 'Lignes centrales',
  TKeys.tutFaceStep2Instruction: 'Ajoutez une ligne centrale verticale et horizontale pour aligner les traits.',
  TKeys.tutFaceStep3Title: 'Mâchoire et menton',
  TKeys.tutFaceStep3Instruction: "Affinez l'ovale en une forme de mâchoire et de menton.",
  TKeys.tutFaceStep4Title: 'Placement des yeux',
  TKeys.tutFaceStep4Instruction: "Marquez la ligne des yeux et répartissez cinq largeurs d'œil sur toute sa longueur.",
  TKeys.tutFaceStep5Title: 'Yeux et sourcils',
  TKeys.tutFaceStep5Instruction: 'Dessinez des yeux en amande sur les deuxième et quatrième repères, puis ajoutez les sourcils au-dessus.',
  TKeys.tutFaceStep6Title: 'Le nez',
  TKeys.tutFaceStep6Instruction: 'Le bas du nez se situe à mi-chemin entre les yeux et le menton.',
  TKeys.tutFaceStep7Title: 'La bouche',
  TKeys.tutFaceStep7Instruction: 'La bouche se situe au tiers du chemin entre le nez et le menton.',
  TKeys.tutFaceStep8Title: 'Oreilles',
  TKeys.tutFaceStep8Instruction: "Les oreilles s'étendent de la ligne des sourcils jusqu'au bas du nez.",
  TKeys.tutFaceStep9Title: 'Cheveux',
  TKeys.tutFaceStep9Instruction: 'Terminez par une ligne de cheveux et quelques mèches pour la texture.',

  // ── Tutorial: draw-a-cat ─────────────────────────────────────────────────
  TKeys.tutCatTitle: "Comment Dessiner le Visage d'un Chat",
  TKeys.tutCatDesc: "Des formes simples à un croquis complet du visage d'un chat",
  TKeys.tutCatStep1Title: 'Le cercle guide',
  TKeys.tutCatStep1Instruction: 'Commencez par un cercle pour la tête, puis ajoutez une croix centrale pour aligner les traits.',
  TKeys.tutCatStep2Title: 'Ajoutez les oreilles',
  TKeys.tutCatStep2Instruction: 'Dessinez deux oreilles triangulaires sur le dessus du cercle, légèrement inclinées vers l\'extérieur.',
  TKeys.tutCatStep3Title: 'Yeux et nez',
  TKeys.tutCatStep3Instruction: 'Placez des yeux en amande sur la ligne centrale, puis un petit nez triangulaire en dessous.',
  TKeys.tutCatStep4Title: 'Bouche et moustaches',
  TKeys.tutCatStep4Instruction: 'Terminez la bouche avec une ligne courbe partant du nez, puis ajoutez les moustaches et la fourrure des joues.',

  // ── Tutorial: draw-a-house ───────────────────────────────────────────────
  TKeys.tutHouseTitle: 'Comment Dessiner une Maison',
  TKeys.tutHouseDesc: "Construisez un cottage douillet à partir de formes de base",
  TKeys.tutHouseStep1Title: 'Le rectangle de base',
  TKeys.tutHouseStep1Instruction: 'Commencez par un simple rectangle pour le mur avant, et une ligne centrale pour garder la symétrie.',
  TKeys.tutHouseStep2Title: 'La ligne de toit',
  TKeys.tutHouseStep2Instruction: 'Ajoutez un toit pointu au-dessus, se rejoignant en un point au-dessus de la ligne centrale.',
  TKeys.tutHouseStep3Title: 'Porte et fenêtres',
  TKeys.tutHouseStep3Instruction: 'Dessinez une porte au milieu et une fenêtre de chaque côté.',
  TKeys.tutHouseStep4Title: 'Ajoutez la cheminée',
  TKeys.tutHouseStep4Instruction: "Dessinez une cheminée rectangulaire s'élevant depuis le bord arrière du toit.",
  TKeys.tutHouseStep5Title: 'Bardeaux du toit',
  TKeys.tutHouseStep5Instruction: 'Remplissez le toit de courtes lignes de bardeaux superposées pour la texture.',
  TKeys.tutHouseStep6Title: 'Ombrage des murs',
  TKeys.tutHouseStep6Instruction: 'Ajoutez des hachures croisées aux murs et au toit pour suggérer ombre et profondeur.',
  TKeys.tutHouseStep7Title: 'Détails finaux',
  TKeys.tutHouseStep7Instruction: 'Terminez avec une poignée de porte, des carreaux de fenêtre et une ligne de sol sous la maison.',

  // ── Tutorial: draw-a-tree ────────────────────────────────────────────────
  TKeys.tutTreeTitle: 'Comment Dessiner un Arbre',
  TKeys.tutTreeDesc: "Faites pousser un chêne complet à partir d'un simple ovale guide",
  TKeys.tutTreeStep1Title: "L'ovale guide",
  TKeys.tutTreeStep1Instruction: "Esquissez un ovale lâche pour la couronne, puis tracez une ligne de tronc droite vers le bas depuis son centre.",
  TKeys.tutTreeStep2Title: 'Tronc et branches',
  TKeys.tutTreeStep2Instruction: "Épaississez le tronc et divisez-le en quelques branches principales atteignant l'ovale.",
  TKeys.tutTreeStep3Title: 'Contour de la couronne',
  TKeys.tutTreeStep3Instruction: "Tracez un contour bosselé, semblable à un nuage, autour de l'ovale pour former le bord feuillu de la couronne.",
  TKeys.tutTreeStep4Title: 'Écorce et racines',
  TKeys.tutTreeStep4Instruction: 'Ajoutez des lignes de texture le long du tronc et quelques lignes de racines évasées à la base.',
  TKeys.tutTreeStep5Title: 'Grappes de feuilles',
  TKeys.tutTreeStep5Instruction: 'Dispersez de petites grappes de feuilles festonnées dans la couronne, en suivant les lignes des branches.',
  TKeys.tutTreeStep6Title: 'Ombrage',
  TKeys.tutTreeStep6Instruction: "Ombrez le dessous de la couronne et un côté du tronc pour donner du volume à l'arbre.",

  // ── Tutorial: draw-a-hand ────────────────────────────────────────────────
  TKeys.tutHandTitle: 'Comment Dessiner une Main',
  TKeys.tutHandDesc: 'Décomposez une main levée en formes simples',
  TKeys.tutHandStep1Title: 'La forme de la paume',
  TKeys.tutHandStep1Instruction: 'Commencez par un carré arrondi pour la paume, puis ajoutez une courte ligne de poignet en dessous.',
  TKeys.tutHandStep2Title: 'Lignes guides des doigts',
  TKeys.tutHandStep2Instruction: 'Ajoutez cinq lignes guides droites en éventail depuis le haut de la paume pour chaque doigt.',
  TKeys.tutHandStep3Title: 'Segments des doigts',
  TKeys.tutHandStep3Instruction: 'Construisez chaque doigt comme des segments de tube empilés le long de sa ligne guide, se rétrécissant légèrement vers la pointe.',
  TKeys.tutHandStep4Title: 'Affinez le contour',
  TKeys.tutHandStep4Instruction: "Nettoyez la silhouette extérieure de la main et des doigts en une seule ligne continue.",
  TKeys.tutHandStep5Title: 'Plis des jointures',
  TKeys.tutHandStep5Instruction: "Ajoutez de courts plis courbes à chaque jointure pour montrer où les doigts se plient.",
  TKeys.tutHandStep6Title: 'Lignes de la paume',
  TKeys.tutHandStep6Instruction: 'Effacez les lignes de construction et ajoutez quelques plis doux à travers la paume.',
  TKeys.tutHandStep7Title: 'Ombrage',
  TKeys.tutHandStep7Instruction: 'Ombrez la base de la paume et les côtés des doigts pour donner du volume à la main.',

  // ── Tutorial: shading-basics ──────────────────────────────────────────────
  TKeys.tutShadingTitle: "Bases de l'Ombrage",
  TKeys.tutShadingDesc: 'Lumière, ombre et forme avec des figures simples',
  TKeys.tutShadingStep1Title: 'Source de lumière',
  TKeys.tutShadingStep1Instruction: 'Choisissez une direction de lumière et gardez-la cohérente sur tout le dessin.',
  TKeys.tutShadingStep2Title: 'Ombre centrale',
  TKeys.tutShadingStep2Instruction: "L'ombre la plus sombre se situe juste après la ligne terminatrice, pas au bord même de la forme.",

  TKeys.categoriesTitle: 'Catégories',
  TKeys.categoriesSubtitle: 'Choisissez un style pour parcourir une sélection d\'images à calquer.',
  TKeys.pickImageToTraceArOrPaper: 'Choisissez une image à calquer en RA ou sur papier',

  TKeys.settingsTitle: 'Paramètres',
  TKeys.sectionDrawing: 'DESSIN',
  TKeys.sectionGeneral: 'GÉNÉRAL',
  TKeys.sectionAboutSupport: 'À PROPOS ET ASSISTANCE',

  TKeys.pressureSensitivity: 'Sensibilité à la pression',
  TKeys.pressureSensitivitySub: 'Pour les stylets compatibles',
  TKeys.leftHandedMode: 'Mode gaucher',
  TKeys.leftHandedModeSub: 'Déplacer la barre d\'outils à gauche',
  TKeys.strokeSmoothing: 'Lissage du trait',
  TKeys.hapticFeedback: 'Retour haptique',
  TKeys.autosave: 'Enregistrement automatique',
  TKeys.autosaveSub: 'Enregistrer les modifications pendant le dessin',
  TKeys.measurementUnit: 'Unité de mesure',

  TKeys.moreApps: 'Plus d\'applications',
  TKeys.shareApp: 'Partager l\'app',
  TKeys.privacyPolicy: 'Politique de confidentialité',
  TKeys.feedback: 'Commentaires',
  TKeys.rateApp: 'Évaluer l\'app',
  TKeys.version: 'Version',

  TKeys.choosePhotoToTrace: 'Choisissez une photo à calquer',
  TKeys.camera: 'Appareil photo',
  TKeys.opacityLabel: 'Opacité',
  TKeys.hideLabel: 'Masquer',
  TKeys.extendLabel: 'Agrandir',
  TKeys.lockLabel: 'Verrouiller',
  TKeys.stepProgress: 'Étape : @current/@total',

  TKeys.errNoCameraFound: 'Aucune caméra trouvée sur cet appareil.',
  TKeys.errCameraStartFailed: 'Impossible de démarrer la caméra. Vérifiez les autorisations.',
  TKeys.errFlashToggleFailed: 'Impossible d\'activer le flash.',
  TKeys.errFreezeFailed: 'Impossible de figer l\'image. Réessayez.',
  TKeys.errImageLoadFailed: 'Impossible de charger cette image : @error',
  TKeys.errImageLoadFailedGeneric: 'Impossible de charger cette image.',
  TKeys.errImageDisplayFailed: 'Cette image n\'a pas pu s\'afficher. Essayez une autre photo.',

  TKeys.nothingToSaveYet: 'Rien à enregistrer pour l\'instant : ce croquis n\'est lié à aucun projet.',
  TKeys.saved: 'Enregistré',

  TKeys.exportTitle: 'Exporter',
  TKeys.sectionFormat: 'FORMAT',
  TKeys.sectionResolution: 'RÉSOLUTION',
  TKeys.flattenLayers: 'Aplatir les calques',
  TKeys.flattenLayersSub: 'Combiner tous les calques visibles en une seule image',
  TKeys.exportedCheck: 'Exporté ✓',
  TKeys.exportSketch: 'Exporter le croquis',
  TKeys.errPermissionDenied: 'L\'autorisation d\'enregistrer les photos a été refusée.',
  TKeys.errPsdComingSoon: 'L\'export PSD arrive bientôt.',
  TKeys.errExportFailed: 'Échec de l\'export : @error',

  TKeys.exportFormatPng: 'PNG',
  TKeys.exportFormatJpg: 'JPG',
  TKeys.exportFormatPdf: 'PDF',
  TKeys.exportFormatPsd: 'PSD (bientôt disponible)',

  TKeys.exportResStandard: 'Standard · 1x',
  TKeys.exportResHigh: 'Haute · 2x',
  TKeys.exportResOriginal: 'Taille de toile d\'origine',

  TKeys.layersTitle: 'Calques',
  TKeys.layerOpacityLabel: 'Opacité',
  TKeys.blendModeLabel: 'Mode de fusion',
  TKeys.duplicate: 'Dupliquer',
  TKeys.delete: 'Supprimer',

  TKeys.blendNormal: 'Normal',
  TKeys.blendMultiply: 'Produit',
  TKeys.blendScreen: 'Superposition',
  TKeys.blendOverlay: 'Incrustation',
  TKeys.blendDarken: 'Obscurcir',
  TKeys.blendLighten: 'Éclaircir',

  TKeys.sketchesTitle: 'Croquis',
  TKeys.newSketch: 'Nouveau croquis',
  TKeys.startYourFirstSketch: 'Commencez votre premier croquis',
  TKeys.sketchesEmptyDesc: 'Les dessins réalisés avec l\'outil croquis apparaissent ici.',

  TKeys.galleryTitle: 'Galerie',
  TKeys.galleryEmptyDesc: 'Les dessins que vous enregistrez apparaîtront ici.',

  TKeys.complementaryLabel: 'Complémentaire',
  TKeys.colorHistoryLabel: 'Historique des couleurs',
  TKeys.hexPrefix: 'HEX #',
  TKeys.noFavoritesYet: 'Aucun favori pour l\'instant : appuyez sur l\'étoile d\'une couleur.',
  TKeys.noPalettesYet: 'Aucune palette pour l\'instant',
  TKeys.renamePalette: 'Renommer la palette',
  TKeys.cancel: 'Annuler',
  TKeys.save: 'Enregistrer',
  TKeys.newPalette: 'Nouvelle palette',

  TKeys.toolsTitle: 'Outils',
  TKeys.sectionUtility: 'UTILITAIRE',
  TKeys.sectionBrushSettings: 'RÉGLAGES DU PINCEAU',
  TKeys.sizeLabel: 'Taille',
  TKeys.hardnessLabel: 'Dureté',

  TKeys.toolPencil: 'Crayon',
  TKeys.toolPen: 'Stylo',
  TKeys.toolMarker: 'Marqueur',
  TKeys.toolAirbrush: 'Aérographe',
  TKeys.toolSmear: 'Estompe',
  TKeys.toolEraser: 'Gomme',
  TKeys.toolFill: 'Remplissage',
  TKeys.toolEyedropper: 'Pipette',
  TKeys.toolShape: 'Forme',
  TKeys.toolText: 'Texte',

  TKeys.categoryBasic: 'Basique',
  TKeys.categoryFineArt: 'Beaux-arts',
  TKeys.categoryMarkers: 'Marqueurs',
  TKeys.categoryArtist: 'Artiste',
  TKeys.categoryPastel: 'Pastel',
  TKeys.categoryTexture: 'Texture',

  TKeys.presetHbPencil: 'Crayon HB',
  TKeys.presetFineLiner: 'Feutre fin',
  TKeys.presetSoftMarker: 'Marqueur doux',
  TKeys.presetAirbrushSoft: 'Aérographe doux',
  TKeys.presetGradePencil: 'Crayon @grade',
  TKeys.presetChiselMarker: 'Marqueur biseauté',
  TKeys.presetBulletMarker: 'Marqueur pointe ronde',
  TKeys.presetBroadMarker: 'Marqueur large',
  TKeys.presetRoundBrush: 'Pinceau rond',
  TKeys.presetFlatBrush: 'Pinceau plat',
  TKeys.presetFanBrush: 'Pinceau éventail',
  TKeys.presetSoftPastel: 'Pastel doux',
  TKeys.presetHardPastel: 'Pastel dur',
  TKeys.presetCrosshatch: 'Hachures croisées',
  TKeys.presetGrain: 'Grain',

  TKeys.paletteYellowOrange: 'Jaune et orange jaunâtre',
  TKeys.paletteWarmOranges: 'Oranges chauds',
  TKeys.paletteReds: 'Rouges',
  TKeys.paletteMagenta: 'Magenta',
  TKeys.palettePurples: 'Violets',
  TKeys.paletteBlues: 'Bleus',
  TKeys.paletteTeals: 'Sarcelles',
  TKeys.paletteGreens: 'Verts',
  TKeys.paletteGreyscale: 'Niveaux de gris',
  TKeys.paletteBrowns: 'Bruns',
  TKeys.palettePrimary: 'Primaires',

  TKeys.categoryLegacy: 'Classique',
  TKeys.categorySynthetic: 'Peinture synthétique',
  TKeys.categoryTraditional: 'Traditionnel',
  TKeys.categoryHalfTone: 'Demi-teinte',
  TKeys.categoryShape: 'Forme',
  TKeys.categorySplatter: 'Éclaboussure',
  TKeys.categoryGlow: 'Lueur',
  TKeys.categorySmudge: 'Estompage',
  TKeys.categoryDesigner: 'Designer',
  TKeys.categoryColorless: 'Incolore',

  TKeys.errCouldNotLoadImages: 'Impossible de charger les images : @error',
  TKeys.noImagesYet: 'Aucune image pour l\'instant',
  TKeys.addImagesToFolder: 'Ajoutez des images à @folder/ et déclarez le dossier dans pubspec.yaml.',
  TKeys.howDoYouWantToTraceThis: 'Comment voulez-vous calquer ceci ?',
  TKeys.arCameraOption: 'Caméra RA',
  TKeys.arCameraSublabel: 'Superposez l\'image à votre vue caméra en direct',
  TKeys.onPaperOption: 'Sur papier',
  TKeys.onPaperSublabel: 'Affichez l\'image à l\'écran et copiez-la à main levée',

  TKeys.drawFromCategory: 'Dessiner depuis @category',
  TKeys.howDoYouWantToTrace2: 'Comment voulez-vous calquer ?',
  TKeys.browseCategoryPresets: 'Vous pourrez parcourir les préréglages @category une fois dans l\'un ou l\'autre mode.',

  TKeys.rename: 'Renommer',
  TKeys.exportLabel: 'Exporter',
  TKeys.renameSketch: 'Renommer le croquis',
  TKeys.deleteSketchQuestion: 'Supprimer le croquis ?',
  TKeys.deleteSketchConfirm: '« @name » sera définitivement supprimé.',

  TKeys.catAnime: 'Anime',
  TKeys.catCartoon: 'Dessin animé',
  TKeys.catPortrait: 'Portrait',
  TKeys.catAnimals: 'Animaux',
  TKeys.catNature: 'Nature',
  TKeys.catObjects: 'Objets',

  TKeys.navHome: 'Accueil',
  TKeys.navLearn: 'Apprendre',
  TKeys.navCategories: 'Catégories',
  TKeys.navSettings: 'Paramètres',

  TKeys.languageSetting: 'Langue',
};