import 'package:sketch_flow/app/localization/translation_keys.dart';

const Map<String, String> hiIN = {
  TKeys.appTitle: 'SketchFlow',
  TKeys.appTagline: 'संवर्धित वास्तविकता में चित्र बनाएं',
  TKeys.loadingYourCanvas: 'आपका कैनवास लोड हो रहा है…',

  TKeys.chooseYourLanguage: 'अपनी भाषा चुनें',
  TKeys.selectPreferredLanguage: 'जारी रखने के लिए अपनी पसंदीदा भाषा चुनें',
  TKeys.continueBtn: 'जारी रखें',

  TKeys.languageNameEnglish: 'अंग्रेज़ी',
  TKeys.languageNameSpanish: 'स्पेनिश',
  TKeys.languageNameFrench: 'फ़्रेंच',
  TKeys.languageNameGerman: 'जर्मन',
  TKeys.languageNameHindi: 'हिन्दी',
  TKeys.languageNameChinese: 'चीनी',

  TKeys.confirmLanguage: 'भाषा की पुष्टि करें',
  TKeys.changeLanguageAnytime: 'आप इसे सेटिंग्स में कभी भी बदल सकते हैं',
  TKeys.selected: 'चयनित',
  TKeys.changeLanguage: 'भाषा बदलें',
  TKeys.confirmAndContinue: 'पुष्टि करें और जारी रखें',

  TKeys.onboardSlide1Title: 'AR में कुछ भी बनाएं',
  TKeys.onboardSlide1Desc:
  'अपने कैमरे का उपयोग करके सीधे वास्तविक दुनिया पर स्केच करके अपनी कल्पना को वास्तविकता में बदलें',
  TKeys.onboardSlide2Title: 'सटीकता के साथ ट्रेस करें',
  TKeys.onboardSlide2Desc:
  'कोई भी फ़ोटो आयात करें और सही लाइन वर्क के लिए समायोज्य ओपेसिटी गाइड के साथ उसे ट्रेस करें',
  TKeys.onboardSlide3Title: 'अपनी कला सहेजें और साझा करें',
  TKeys.onboardSlide3Desc:
  'पूर्ण स्केच को अपनी गैलरी में निर्यात करें और अपनी रचनात्मक प्रक्रिया को दुनिया के साथ साझा करें',
  TKeys.skip: 'छोड़ें',
  TKeys.next: 'अगला',
  TKeys.getStarted: 'शुरू करें',

  TKeys.arDrawingApp: 'AR ड्राइंग ऐप',
  TKeys.helloArtist: 'नमस्ते, कलाकार!',
  TKeys.startADrawing: 'ड्राइंग शुरू करें',
  TKeys.traceAnyPhoto: 'गैलरी या कैमरे की किसी भी फ़ोटो को AR में या कागज़ पर ट्रेस करें।',
  TKeys.arCamera: 'AR कैमरा',
  TKeys.onPaper: 'कागज़ पर',
  TKeys.exploreFeatures: 'सुविधाएं देखें',
  TKeys.sketch: 'स्केच',
  TKeys.categories: 'श्रेणियाँ',
  TKeys.gallery: 'गैलरी',
  TKeys.seeAll: 'सभी देखें',
  TKeys.pickImageToTrace: 'AR या कागज़ पर ट्रेस करने के लिए एक छवि चुनें',

  TKeys.leavingSoSoon: 'क्या आप अभी जा रहे हैं?',
  TKeys.missYourCreations: 'हमें आपकी शानदार AR कृतियों की याद आएगी!',
  TKeys.stayAndKeepDrawing: 'रुकें और ड्राइंग जारी रखें',
  TKeys.leave: 'छोड़ें',

  TKeys.learnToDraw: 'ड्राइंग सीखें',
  TKeys.stepByStepTutorials: 'चरण-दर-चरण ट्यूटोरियल जिन्हें आप साथ-साथ ट्रेस कर सकते हैं',
  TKeys.arCameraSublabelTutorial: 'अपने लाइव कैमरा दृश्य पर ट्यूटोरियल को चरणबद्ध करें',
  TKeys.onPaperSublabelTutorial: 'स्क्रीन पर ट्यूटोरियल को चरणबद्ध करें और आंख से कॉपी करें',
  TKeys.howDoYouWantToTrace: 'आप इसे कैसे ट्रेस करना चाहते हैं?',
  TKeys.stepsCount: 'चरण',

  TKeys.stepLabel: 'चरण',
  TKeys.arCameraSublabelStep: 'इस चरण को अपने लाइव कैमरा दृश्य पर ओवरले करें',
  TKeys.onPaperSublabelStep: 'इस चरण को स्क्रीन पर दिखाएं और आंख से कॉपी करें',

  // ── Shared difficulty ─────────────────────────────────────────────────
  TKeys.difficultyBeginner: 'शुरुआती',
  TKeys.difficultyIntermediate: 'मध्यम',

  // ── Tutorial: draw-a-face ────────────────────────────────────────────────
  TKeys.tutFaceTitle: 'चेहरा कैसे बनाएं',
  TKeys.tutFaceDesc: 'चरण दर चरण चेहरे के अनुपात सीखें',
  TKeys.tutFaceStep1Title: 'गाइड अंडाकार',
  TKeys.tutFaceStep1Instruction: 'सिर के आकार के लिए एक साधारण अंडाकार से शुरू करें।',
  TKeys.tutFaceStep2Title: 'केंद्र रेखाएं',
  TKeys.tutFaceStep2Instruction: 'विशेषताओं को संरेखित करने के लिए एक ऊर्ध्वाधर और क्षैतिज केंद्र रेखा जोड़ें।',
  TKeys.tutFaceStep3Title: 'जबड़ा और ठुड्डी',
  TKeys.tutFaceStep3Instruction: 'अंडाकार को जबड़े और ठुड्डी के आकार में परिष्कृत करें।',
  TKeys.tutFaceStep4Title: 'आंखों की स्थिति',
  TKeys.tutFaceStep4Instruction: 'आंख की रेखा चिह्नित करें और उसके साथ पांच आंख-चौड़ाई की दूरी बनाएं।',
  TKeys.tutFaceStep5Title: 'आंखें और भौहें',
  TKeys.tutFaceStep5Instruction: 'दूसरे और चौथे निशान पर बादाम के आकार की आंखें बनाएं, फिर ऊपर भौहें जोड़ें।',
  TKeys.tutFaceStep6Title: 'नाक',
  TKeys.tutFaceStep6Instruction: 'नाक का निचला भाग आंखों और ठुड्डी के बीच में स्थित होता है।',
  TKeys.tutFaceStep7Title: 'मुंह',
  TKeys.tutFaceStep7Instruction: 'मुंह नाक से ठुड्डी तक के रास्ते के एक तिहाई हिस्से में स्थित होता है।',
  TKeys.tutFaceStep8Title: 'कान',
  TKeys.tutFaceStep8Instruction: 'कान भौंह रेखा से नाक के निचले हिस्से तक फैले होते हैं।',
  TKeys.tutFaceStep9Title: 'बाल',
  TKeys.tutFaceStep9Instruction: 'बालों की रेखा और बनावट के लिए कुछ लटों के साथ समाप्त करें।',

  // ── Tutorial: draw-a-cat ─────────────────────────────────────────────────
  TKeys.tutCatTitle: 'बिल्ली का चेहरा कैसे बनाएं',
  TKeys.tutCatDesc: 'साधारण आकृतियों से एक पूर्ण बिल्ली चेहरे के स्केच तक',
  TKeys.tutCatStep1Title: 'गाइड वृत्त',
  TKeys.tutCatStep1Instruction: 'सिर के लिए एक वृत्त से शुरू करें, फिर विशेषताओं को संरेखित करने के लिए एक केंद्र क्रॉस जोड़ें।',
  TKeys.tutCatStep2Title: 'कान जोड़ें',
  TKeys.tutCatStep2Instruction: 'वृत्त के ऊपर दो त्रिकोणीय कान बनाएं, थोड़ा बाहर की ओर झुके हुए।',
  TKeys.tutCatStep3Title: 'आंखें और नाक',
  TKeys.tutCatStep3Instruction: 'केंद्र रेखा पर बादाम के आकार की आंखें रखें, फिर नीचे एक छोटी त्रिकोणीय नाक बनाएं।',
  TKeys.tutCatStep4Title: 'मुंह और मूंछें',
  TKeys.tutCatStep4Instruction: 'नाक से एक घुमावदार रेखा के साथ मुंह पूरा करें, फिर मूंछें और गाल के बाल जोड़ें।',

  // ── Tutorial: draw-a-house ───────────────────────────────────────────────
  TKeys.tutHouseTitle: 'घर कैसे बनाएं',
  TKeys.tutHouseDesc: 'बुनियादी आकृतियों से एक आरामदायक घर बनाएं',
  TKeys.tutHouseStep1Title: 'आधार आयत',
  TKeys.tutHouseStep1Instruction: 'सामने की दीवार के लिए एक साधारण आयत से शुरू करें, और चीजों को सममित रखने के लिए एक केंद्र रेखा बनाएं।',
  TKeys.tutHouseStep2Title: 'छत की रेखा',
  TKeys.tutHouseStep2Instruction: 'ऊपर एक नुकीली छत जोड़ें, जो केंद्र रेखा के ऊपर एक बिंदु पर मिलती है।',
  TKeys.tutHouseStep3Title: 'दरवाज़ा और खिड़कियां',
  TKeys.tutHouseStep3Instruction: 'बीच में एक दरवाज़ा और उसके प्रत्येक तरफ एक खिड़की बनाएं।',
  TKeys.tutHouseStep4Title: 'चिमनी जोड़ें',
  TKeys.tutHouseStep4Instruction: 'छत के पिछले किनारे से उठती हुई एक आयताकार चिमनी बनाएं।',
  TKeys.tutHouseStep5Title: 'छत की टाइलें',
  TKeys.tutHouseStep5Instruction: 'बनावट के लिए छत को छोटी ओवरलैपिंग टाइल रेखाओं से भरें।',
  TKeys.tutHouseStep6Title: 'दीवारों की शेडिंग',
  TKeys.tutHouseStep6Instruction: 'छाया और गहराई दर्शाने के लिए दीवारों और छत पर क्रॉसहैचिंग जोड़ें।',
  TKeys.tutHouseStep7Title: 'अंतिम विवरण',
  TKeys.tutHouseStep7Instruction: 'दरवाज़े की घुंडी, खिड़की के पैन, और घर के नीचे एक ज़मीन रेखा के साथ समाप्त करें।',

  // ── Tutorial: draw-a-tree ────────────────────────────────────────────────
  TKeys.tutTreeTitle: 'पेड़ कैसे बनाएं',
  TKeys.tutTreeDesc: 'एक साधारण अंडाकार गाइड से एक पूर्ण ओक का पेड़ उगाएं',
  TKeys.tutTreeStep1Title: 'गाइड अंडाकार',
  TKeys.tutTreeStep1Instruction: 'छतरी के लिए एक ढीला अंडाकार बनाएं, फिर उसके केंद्र से सीधे नीचे एक तने की रेखा खींचें।',
  TKeys.tutTreeStep2Title: 'तना और शाखाएं',
  TKeys.tutTreeStep2Instruction: 'तने को मोटा करें और इसे अंडाकार में ऊपर पहुंचने वाली कुछ मुख्य शाखाओं में विभाजित करें।',
  TKeys.tutTreeStep3Title: 'छतरी की रूपरेखा',
  TKeys.tutTreeStep3Instruction: 'पत्तेदार छतरी के किनारे को बनाने के लिए अंडाकार के चारों ओर एक ऊबड़-खाबड़, बादल जैसी रूपरेखा बनाएं।',
  TKeys.tutTreeStep4Title: 'छाल और जड़ें',
  TKeys.tutTreeStep4Instruction: 'तने के साथ बनावट रेखाएं जोड़ें और आधार पर फैली हुई कुछ जड़ रेखाएं जोड़ें।',
  TKeys.tutTreeStep5Title: 'पत्तों के गुच्छे',
  TKeys.tutTreeStep5Instruction: 'शाखा रेखाओं का अनुसरण करते हुए छतरी के अंदर छोटे झालरदार पत्तों के गुच्छे बिखेरें।',
  TKeys.tutTreeStep6Title: 'शेडिंग',
  TKeys.tutTreeStep6Instruction: 'पेड़ को आकार देने के लिए छतरी के निचले हिस्से और तने के एक तरफ छाया डालें।',

  // ── Tutorial: draw-a-hand ────────────────────────────────────────────────
  TKeys.tutHandTitle: 'हाथ कैसे बनाएं',
  TKeys.tutHandDesc: 'उठे हुए हाथ को साधारण आकृतियों में विभाजित करें',
  TKeys.tutHandStep1Title: 'हथेली का आकार',
  TKeys.tutHandStep1Instruction: 'हथेली के लिए एक गोल वर्ग से शुरू करें, फिर उसके नीचे एक छोटी कलाई रेखा जोड़ें।',
  TKeys.tutHandStep2Title: 'उंगली की गाइड रेखाएं',
  TKeys.tutHandStep2Instruction: 'प्रत्येक उंगली के लिए हथेली के ऊपरी हिस्से से पंखे की तरह फैलती पांच सीधी गाइड रेखाएं जोड़ें।',
  TKeys.tutHandStep3Title: 'उंगली के खंड',
  TKeys.tutHandStep3Instruction: 'प्रत्येक उंगली को उसकी गाइड रेखा के साथ ढेर किए गए ट्यूब खंडों के रूप में बनाएं, जो सिरे की ओर थोड़ा पतला हो।',
  TKeys.tutHandStep4Title: 'रूपरेखा को परिष्कृत करें',
  TKeys.tutHandStep4Instruction: 'हाथ और उंगलियों की बाहरी आकृति को एक निरंतर रेखा में साफ करें।',
  TKeys.tutHandStep5Title: 'गांठों की सिलवटें',
  TKeys.tutHandStep5Instruction: 'यह दिखाने के लिए कि उंगलियां कहां मुड़ती हैं, प्रत्येक गांठ पर छोटी घुमावदार सिलवटें जोड़ें।',
  TKeys.tutHandStep6Title: 'हथेली की रेखाएं',
  TKeys.tutHandStep6Instruction: 'निर्माण रेखाओं को मिटाएं और हथेली में कुछ मुलायम सिलवटें जोड़ें।',
  TKeys.tutHandStep7Title: 'शेडिंग',
  TKeys.tutHandStep7Instruction: 'हाथ को आयतन देने के लिए हथेली के आधार और उंगलियों के किनारों पर छाया डालें।',

  // ── Tutorial: shading-basics ──────────────────────────────────────────────
  TKeys.tutShadingTitle: 'शेडिंग की मूल बातें',
  TKeys.tutShadingDesc: 'साधारण आकृतियों के साथ प्रकाश, छाया और रूप',
  TKeys.tutShadingStep1Title: 'प्रकाश स्रोत',
  TKeys.tutShadingStep1Instruction: 'एक प्रकाश दिशा चुनें और उसे पूरे चित्र में स्थिर रखें।',
  TKeys.tutShadingStep2Title: 'मुख्य छाया',
  TKeys.tutShadingStep2Instruction: 'सबसे गहरी छाया टर्मिनेटर रेखा के ठीक बाद स्थित होती है, आकृति के बिल्कुल किनारे पर नहीं।',

  TKeys.categoriesTitle: 'श्रेणियाँ',
  TKeys.categoriesSubtitle: 'ट्रेस करने के लिए चुनी हुई तस्वीरों को देखने के लिए एक स्टाइल चुनें।',
  TKeys.pickImageToTraceArOrPaper: 'AR या कागज़ पर ट्रेस करने के लिए एक तस्वीर चुनें',

  TKeys.settingsTitle: 'सेटिंग्स',
  TKeys.sectionDrawing: 'ड्रॉइंग',
  TKeys.sectionGeneral: 'सामान्य',
  TKeys.sectionAboutSupport: 'जानकारी और सहायता',

  TKeys.pressureSensitivity: 'प्रेशर सेंसिटिविटी',
  TKeys.pressureSensitivitySub: 'ऐसे स्टाइलस के लिए जो इसे सपोर्ट करते हैं',
  TKeys.leftHandedMode: 'बाएं हाथ का मोड',
  TKeys.leftHandedModeSub: 'टूल डॉक को बाईं ओर ले जाएं',
  TKeys.strokeSmoothing: 'स्ट्रोक स्मूदिंग',
  TKeys.hapticFeedback: 'हैप्टिक फ़ीडबैक',
  TKeys.autosave: 'ऑटोसेव',
  TKeys.autosaveSub: 'ड्रॉ करते समय बदलाव सेव करें',
  TKeys.measurementUnit: 'माप की इकाई',

  TKeys.moreApps: 'और ऐप्स',
  TKeys.shareApp: 'ऐप शेयर करें',
  TKeys.privacyPolicy: 'गोपनीयता नीति',
  TKeys.feedback: 'फ़ीडबैक',
  TKeys.rateApp: 'ऐप को रेट करें',
  TKeys.version: 'वर्शन',

  TKeys.choosePhotoToTrace: 'ट्रेस करने के लिए एक फ़ोटो चुनें',
  TKeys.camera: 'कैमरा',
  TKeys.opacityLabel: 'ओपैसिटी',
  TKeys.hideLabel: 'छिपाएं',
  TKeys.extendLabel: 'बड़ा करें',
  TKeys.lockLabel: 'लॉक करें',
  TKeys.stepProgress: 'चरण: @current/@total',

  TKeys.errNoCameraFound: 'इस डिवाइस पर कोई कैमरा नहीं मिला।',
  TKeys.errCameraStartFailed: 'कैमरा शुरू नहीं हो सका। अनुमतियां जांचें।',
  TKeys.errFlashToggleFailed: 'फ़्लैश टॉगल नहीं हो सका।',
  TKeys.errFreezeFailed: 'फ़्रेम फ़्रीज़ नहीं हो सका। फिर से कोशिश करें।',
  TKeys.errImageLoadFailed: 'यह तस्वीर लोड नहीं हो सकी: @error',
  TKeys.errImageLoadFailedGeneric: 'यह तस्वीर लोड नहीं हो सकी।',
  TKeys.errImageDisplayFailed: 'यह तस्वीर दिखाई नहीं जा सकी। कोई दूसरी फ़ोटो आज़माएं।',

  TKeys.nothingToSaveYet: 'अभी सेव करने के लिए कुछ नहीं है — यह स्केच किसी प्रोजेक्ट से जुड़ा नहीं है।',
  TKeys.saved: 'सेव हो गया',

  TKeys.exportTitle: 'एक्सपोर्ट',
  TKeys.sectionFormat: 'फ़ॉर्मेट',
  TKeys.sectionResolution: 'रिज़ॉल्यूशन',
  TKeys.flattenLayers: 'लेयर्स फ़्लैटन करें',
  TKeys.flattenLayersSub: 'सभी दिखने वाली लेयर्स को एक तस्वीर में मिलाएं',
  TKeys.exportedCheck: 'एक्सपोर्ट हो गया ✓',
  TKeys.exportSketch: 'स्केच एक्सपोर्ट करें',
  TKeys.errPermissionDenied: 'फ़ोटो सेव करने की अनुमति अस्वीकार कर दी गई।',
  TKeys.errPsdComingSoon: 'PSD एक्सपोर्ट जल्द आ रहा है।',
  TKeys.errExportFailed: 'एक्सपोर्ट विफल: @error',

  TKeys.exportFormatPng: 'PNG',
  TKeys.exportFormatJpg: 'JPG',
  TKeys.exportFormatPdf: 'PDF',
  TKeys.exportFormatPsd: 'PSD (जल्द आ रहा है)',

  TKeys.exportResStandard: 'स्टैंडर्ड · 1x',
  TKeys.exportResHigh: 'हाई · 2x',
  TKeys.exportResOriginal: 'मूल कैनवास आकार',

  TKeys.layersTitle: 'लेयर्स',
  TKeys.layerOpacityLabel: 'ओपैसिटी',
  TKeys.blendModeLabel: 'ब्लेंड मोड',
  TKeys.duplicate: 'डुप्लिकेट करें',
  TKeys.delete: 'हटाएं',

  TKeys.blendNormal: 'नॉर्मल',
  TKeys.blendMultiply: 'मल्टीप्लाई',
  TKeys.blendScreen: 'स्क्रीन',
  TKeys.blendOverlay: 'ओवरले',
  TKeys.blendDarken: 'डार्कन',
  TKeys.blendLighten: 'लाइटन',

  TKeys.sketchesTitle: 'स्केच',
  TKeys.newSketch: 'नया स्केच',
  TKeys.startYourFirstSketch: 'अपना पहला स्केच शुरू करें',
  TKeys.sketchesEmptyDesc: 'स्केच टूल से बनाई गई ड्रॉइंग यहां दिखाई देंगी।',

  TKeys.galleryTitle: 'गैलरी',
  TKeys.galleryEmptyDesc: 'आपकी सेव की गई ड्रॉइंग यहां दिखाई देंगी।',

  TKeys.complementaryLabel: 'पूरक रंग',
  TKeys.colorHistoryLabel: 'रंग इतिहास',
  TKeys.hexPrefix: 'HEX #',
  TKeys.noFavoritesYet: 'अभी तक कोई पसंदीदा नहीं — किसी भी रंग पर स्टार टैप करें।',
  TKeys.noPalettesYet: 'अभी तक कोई पैलेट नहीं',
  TKeys.renamePalette: 'पैलेट का नाम बदलें',
  TKeys.cancel: 'रद्द करें',
  TKeys.save: 'सेव करें',
  TKeys.newPalette: 'नया पैलेट',

  TKeys.toolsTitle: 'टूल्स',
  TKeys.sectionUtility: 'यूटिलिटी',
  TKeys.sectionBrushSettings: 'ब्रश सेटिंग्स',
  TKeys.sizeLabel: 'आकार',
  TKeys.hardnessLabel: 'कठोरता',

  TKeys.toolPencil: 'पेंसिल',
  TKeys.toolPen: 'पेन',
  TKeys.toolMarker: 'मार्कर',
  TKeys.toolAirbrush: 'एयरब्रश',
  TKeys.toolSmear: 'स्मियर',
  TKeys.toolEraser: 'इरेज़र',
  TKeys.toolFill: 'फ़िल',
  TKeys.toolEyedropper: 'आईड्रॉपर',
  TKeys.toolShape: 'आकृति',
  TKeys.toolText: 'टेक्स्ट',

  TKeys.categoryBasic: 'बेसिक',
  TKeys.categoryFineArt: 'फ़ाइन आर्ट',
  TKeys.categoryMarkers: 'मार्कर',
  TKeys.categoryArtist: 'आर्टिस्ट',
  TKeys.categoryPastel: 'पेस्टल',
  TKeys.categoryTexture: 'टेक्सचर',

  TKeys.presetHbPencil: 'HB पेंसिल',
  TKeys.presetFineLiner: 'फ़ाइन लाइनर',
  TKeys.presetSoftMarker: 'सॉफ़्ट मार्कर',
  TKeys.presetAirbrushSoft: 'सॉफ़्ट एयरब्रश',
  TKeys.presetGradePencil: '@grade पेंसिल',
  TKeys.presetChiselMarker: 'चिज़ल मार्कर',
  TKeys.presetBulletMarker: 'बुलेट मार्कर',
  TKeys.presetBroadMarker: 'ब्रॉड मार्कर',
  TKeys.presetRoundBrush: 'राउंड ब्रश',
  TKeys.presetFlatBrush: 'फ़्लैट ब्रश',
  TKeys.presetFanBrush: 'फ़ैन ब्रश',
  TKeys.presetSoftPastel: 'सॉफ़्ट पेस्टल',
  TKeys.presetHardPastel: 'हार्ड पेस्टल',
  TKeys.presetCrosshatch: 'क्रॉसहैच',
  TKeys.presetGrain: 'ग्रेन',

  TKeys.paletteYellowOrange: 'पीला और पीला-नारंगी',
  TKeys.paletteWarmOranges: 'गर्म नारंगी रंग',
  TKeys.paletteReds: 'लाल रंग',
  TKeys.paletteMagenta: 'मैजेंटा',
  TKeys.palettePurples: 'बैंगनी रंग',
  TKeys.paletteBlues: 'नीले रंग',
  TKeys.paletteTeals: 'टील रंग',
  TKeys.paletteGreens: 'हरे रंग',
  TKeys.paletteGreyscale: 'ग्रेस्केल',
  TKeys.paletteBrowns: 'भूरे रंग',
  TKeys.palettePrimary: 'प्राथमिक रंग',

  TKeys.categoryLegacy: 'लेगेसी',
  TKeys.categorySynthetic: 'सिंथेटिक पेंट',
  TKeys.categoryTraditional: 'पारंपरिक',
  TKeys.categoryHalfTone: 'हाफ़ टोन',
  TKeys.categoryShape: 'आकृति',
  TKeys.categorySplatter: 'स्प्लैटर',
  TKeys.categoryGlow: 'चमक',
  TKeys.categorySmudge: 'स्मज',
  TKeys.categoryDesigner: 'डिज़ाइनर',
  TKeys.categoryColorless: 'रंगहीन',

  TKeys.errCouldNotLoadImages: 'तस्वीरें लोड नहीं हो सकीं: @error',
  TKeys.noImagesYet: 'अभी तक कोई तस्वीर नहीं',
  TKeys.addImagesToFolder: '@folder/ में तस्वीरें जोड़ें और pubspec.yaml में फ़ोल्डर घोषित करें।',
  TKeys.howDoYouWantToTraceThis: 'आप इसे कैसे ट्रेस करना चाहते हैं?',
  TKeys.arCameraOption: 'AR कैमरा',
  TKeys.arCameraSublabel: 'तस्वीर को अपने लाइव कैमरा व्यू पर ओवरले करें',
  TKeys.onPaperOption: 'कागज़ पर',
  TKeys.onPaperSublabel: 'तस्वीर को स्क्रीन पर दिखाएं और उसे देखकर बनाएं',

  TKeys.drawFromCategory: '@category से ड्रॉ करें',
  TKeys.howDoYouWantToTrace2: 'आप कैसे ट्रेस करना चाहते हैं?',
  TKeys.browseCategoryPresets: 'किसी भी मोड में जाने के बाद आप @category प्रीसेट ब्राउज़ कर सकते हैं।',

  TKeys.rename: 'नाम बदलें',
  TKeys.exportLabel: 'एक्सपोर्ट',
  TKeys.renameSketch: 'स्केच का नाम बदलें',
  TKeys.deleteSketchQuestion: 'स्केच हटाएं?',
  TKeys.deleteSketchConfirm: '"@name" स्थायी रूप से हटा दिया जाएगा।',

  TKeys.catAnime: 'एनीमे',
  TKeys.catCartoon: 'कार्टून',
  TKeys.catPortrait: 'पोर्ट्रेट',
  TKeys.catAnimals: 'जानवर',
  TKeys.catNature: 'प्रकृति',
  TKeys.catObjects: 'वस्तुएं',

  TKeys.navHome: 'होम',
  TKeys.navLearn: 'सीखें',
  TKeys.navCategories: 'श्रेणियाँ',
  TKeys.navSettings: 'सेटिंग्स',

  TKeys.languageSetting: 'भाषा',

  TKeys.preparingYourExperience: 'बस एक पल...',
  TKeys.errCameraPermissionDenied: 'कैमरा की अनुमति नहीं दी गई',
  TKeys.errGalleryPermissionDenied: 'गैलरी की अनुमति अस्वीकार कर दी गई',

  TKeys.notifications: 'नोटिफ़िकेशन',
  TKeys.notificationsEnabledSub: 'आपको अपडेट और रिमाइंडर मिलेंगे।',
  TKeys.notificationsDisabledSub: 'सिस्टम सेटिंग्स में चालू करने के लिए टैप करें',
};