import 'package:sketch_flow/app/localization/translation_keys.dart';

const Map<String, String> zhCN = {
  TKeys.appTitle: 'SketchFlow',
  TKeys.appTagline: '在增强现实中绘图',
  TKeys.loadingYourCanvas: '正在加载您的画布…',

  TKeys.chooseYourLanguage: '选择您的语言',
  TKeys.selectPreferredLanguage: '选择您偏好的语言以继续',
  TKeys.continueBtn: '继续',

  TKeys.languageNameEnglish: '英语',
  TKeys.languageNameSpanish: '西班牙语',
  TKeys.languageNameFrench: '法语',
  TKeys.languageNameGerman: '德语',
  TKeys.languageNameHindi: '印地语',
  TKeys.languageNameChinese: '中文',

  TKeys.confirmLanguage: '确认语言',
  TKeys.changeLanguageAnytime: '您可以随时在设置中更改此项',
  TKeys.selected: '已选择',
  TKeys.changeLanguage: '更改语言',
  TKeys.confirmAndContinue: '确认并继续',

  TKeys.onboardSlide1Title: '在AR中绘制任何东西',
  TKeys.onboardSlide1Desc: '使用相机直接在现实世界中素描，将您的想象力变为现实',
  TKeys.onboardSlide2Title: '精确描摹',
  TKeys.onboardSlide2Desc: '导入任意照片，通过可调节的透明度参考线进行精确描摹',
  TKeys.onboardSlide3Title: '保存并分享您的作品',
  TKeys.onboardSlide3Desc: '将完成的素描导出到相册，与全世界分享您的创作过程',
  TKeys.skip: '跳过',
  TKeys.next: '下一步',
  TKeys.getStarted: '开始使用',

  TKeys.arDrawingApp: 'AR 绘图应用',
  TKeys.helloArtist: '你好，艺术家！',
  TKeys.startADrawing: '开始绘画',
  TKeys.traceAnyPhoto: '通过AR或纸上描摹相册或相机中的任意照片。',
  TKeys.arCamera: 'AR 相机',
  TKeys.onPaper: '纸上',
  TKeys.exploreFeatures: '探索功能',
  TKeys.sketch: '素描',
  TKeys.categories: '分类',
  TKeys.gallery: '相册',
  TKeys.seeAll: '查看全部',
  TKeys.pickImageToTrace: '选择一张图片以AR或纸上方式描摹',

  TKeys.leavingSoSoon: '这就要走了吗？',
  TKeys.missYourCreations: '我们会想念你精彩的AR作品！',
  TKeys.stayAndKeepDrawing: '留下继续绘画',
  TKeys.leave: '离开',

  TKeys.learnToDraw: '学习绘画',
  TKeys.stepByStepTutorials: '可以边看边描摹的分步教程',
  TKeys.arCameraSublabelTutorial: '在实时相机画面上逐步跟随教程',
  TKeys.onPaperSublabelTutorial: '在屏幕上逐步跟随教程并用眼睛临摹',
  TKeys.howDoYouWantToTrace: '您想如何描摹这个？',
  TKeys.stepsCount: '步骤',

  TKeys.stepLabel: '步骤',
  TKeys.arCameraSublabelStep: '将此步骤叠加在您的实时相机画面上',
  TKeys.onPaperSublabelStep: '在屏幕上显示此步骤并用眼睛临摹',

  // ── Shared difficulty ─────────────────────────────────────────────────
  TKeys.difficultyBeginner: '初级',
  TKeys.difficultyIntermediate: '中级',

  // ── Tutorial: draw-a-face ────────────────────────────────────────────────
  TKeys.tutFaceTitle: '如何画一张脸',
  TKeys.tutFaceDesc: '循序渐进学习脸部比例',
  TKeys.tutFaceStep1Title: '基础椭圆',
  TKeys.tutFaceStep1Instruction: '先画一个简单的椭圆作为头部形状。',
  TKeys.tutFaceStep2Title: '中心线',
  TKeys.tutFaceStep2Instruction: '添加一条竖线和一条横线,用来对齐五官位置。',
  TKeys.tutFaceStep3Title: '下颌和下巴',
  TKeys.tutFaceStep3Instruction: '将椭圆细化为下颌和下巴的形状。',
  TKeys.tutFaceStep4Title: '眼睛定位',
  TKeys.tutFaceStep4Instruction: '标出眼线,并在其上均分出五个眼宽的间距。',
  TKeys.tutFaceStep5Title: '眼睛和眉毛',
  TKeys.tutFaceStep5Instruction: '在第二和第四个标记处画出杏仁形眼睛,再在上方添加眉毛。',
  TKeys.tutFaceStep6Title: '鼻子',
  TKeys.tutFaceStep6Instruction: '鼻底位于眼睛和下巴连线的中点处。',
  TKeys.tutFaceStep7Title: '嘴巴',
  TKeys.tutFaceStep7Instruction: '嘴巴位于鼻子到下巴距离的三分之一处。',
  TKeys.tutFaceStep8Title: '耳朵',
  TKeys.tutFaceStep8Instruction: '耳朵从眉线延伸到鼻底的位置。',
  TKeys.tutFaceStep9Title: '头发',
  TKeys.tutFaceStep9Instruction: '最后画出发际线,并添加几缕发丝表现质感。',

  // ── Tutorial: draw-a-cat ─────────────────────────────────────────────────
  TKeys.tutCatTitle: '如何画猫脸',
  TKeys.tutCatDesc: '从简单形状到完整的猫脸素描',
  TKeys.tutCatStep1Title: '基础圆形',
  TKeys.tutCatStep1Instruction: '先画一个圆形作为头部,再添加一条十字中心线用来对齐五官。',
  TKeys.tutCatStep2Title: '添加耳朵',
  TKeys.tutCatStep2Instruction: '在圆形顶部画两只三角形耳朵,略微向外倾斜。',
  TKeys.tutCatStep3Title: '眼睛和鼻子',
  TKeys.tutCatStep3Instruction: '在中心线上画出杏仁形眼睛,再在下方画一个小三角形鼻子。',
  TKeys.tutCatStep4Title: '嘴巴和胡须',
  TKeys.tutCatStep4Instruction: '从鼻子处画一条曲线完成嘴巴,再添加胡须和脸颊绒毛。',

  // ── Tutorial: draw-a-house ───────────────────────────────────────────────
  TKeys.tutHouseTitle: '如何画房子',
  TKeys.tutHouseDesc: '用基础形状搭建一座温馨小屋',
  TKeys.tutHouseStep1Title: '基础矩形',
  TKeys.tutHouseStep1Instruction: '先画一个简单的矩形作为正面墙体,并添加一条中心线保持对称。',
  TKeys.tutHouseStep2Title: '屋顶轮廓',
  TKeys.tutHouseStep2Instruction: '在顶部添加一个尖屋顶,顶点落在中心线上方。',
  TKeys.tutHouseStep3Title: '门窗',
  TKeys.tutHouseStep3Instruction: '在中间画一扇门,两侧各画一扇窗户。',
  TKeys.tutHouseStep4Title: '添加烟囱',
  TKeys.tutHouseStep4Instruction: '从屋顶后边缘画出一个矩形烟囱。',
  TKeys.tutHouseStep5Title: '屋顶瓦片',
  TKeys.tutHouseStep5Instruction: '在屋顶上填满短小重叠的瓦片线条以表现质感。',
  TKeys.tutHouseStep6Title: '墙面阴影',
  TKeys.tutHouseStep6Instruction: '在墙面和屋顶添加交叉排线,表现阴影与深度。',
  TKeys.tutHouseStep7Title: '最终细节',
  TKeys.tutHouseStep7Instruction: '最后添加门把手、窗格,以及房屋下方的地面线。',

  // ── Tutorial: draw-a-tree ────────────────────────────────────────────────
  TKeys.tutTreeTitle: '如何画树',
  TKeys.tutTreeDesc: '从简单的椭圆引导线画出一棵完整的橡树',
  TKeys.tutTreeStep1Title: '基础椭圆',
  TKeys.tutTreeStep1Instruction: '画一个松散的椭圆作为树冠,再从中心向下画一条树干线。',
  TKeys.tutTreeStep2Title: '树干和树枝',
  TKeys.tutTreeStep2Instruction: '加粗树干,并分出几根主枝伸向椭圆内部。',
  TKeys.tutTreeStep3Title: '树冠轮廓',
  TKeys.tutTreeStep3Instruction: '沿着椭圆勾画出凹凸不平、云朵状的轮廓线,形成树冠边缘。',
  TKeys.tutTreeStep4Title: '树皮和树根',
  TKeys.tutTreeStep4Instruction: '在树干上添加纹理线条,并在底部画出几条外展的树根线。',
  TKeys.tutTreeStep5Title: '树叶簇',
  TKeys.tutTreeStep5Instruction: '沿着树枝线,在树冠内散布小片的扇贝状树叶簇。',
  TKeys.tutTreeStep6Title: '阴影',
  TKeys.tutTreeStep6Instruction: '为树冠底部和树干一侧添加阴影,使树木更具立体感。',

  // ── Tutorial: draw-a-hand ────────────────────────────────────────────────
  TKeys.tutHandTitle: '如何画手',
  TKeys.tutHandDesc: '将举起的手拆解为简单形状',
  TKeys.tutHandStep1Title: '手掌形状',
  TKeys.tutHandStep1Instruction: '先画一个圆角方形作为手掌,再在下方添加一条短短的手腕线。',
  TKeys.tutHandStep2Title: '手指引导线',
  TKeys.tutHandStep2Instruction: '从手掌顶部呈扇形画出五条直线,分别对应每根手指。',
  TKeys.tutHandStep3Title: '手指分段',
  TKeys.tutHandStep3Instruction: '沿引导线将每根手指画成堆叠的圆柱形段,末端略微收窄。',
  TKeys.tutHandStep4Title: '细化轮廓',
  TKeys.tutHandStep4Instruction: '整理手和手指的外部轮廓,连成一条连贯的线条。',
  TKeys.tutHandStep5Title: '关节褶皱',
  TKeys.tutHandStep5Instruction: '在每个关节处添加短短的弧形褶皱,表现手指弯曲的位置。',
  TKeys.tutHandStep6Title: '手掌纹路',
  TKeys.tutHandStep6Instruction: '擦除辅助线,在手掌上添加几条柔和的纹路。',
  TKeys.tutHandStep7Title: '阴影',
  TKeys.tutHandStep7Instruction: '在手掌根部和手指两侧添加阴影,表现手部的立体感。',

  // ── Tutorial: shading-basics ──────────────────────────────────────────────
  TKeys.tutShadingTitle: '阴影基础',
  TKeys.tutShadingDesc: '用简单形状理解光线、阴影与体积',
  TKeys.tutShadingStep1Title: '光源方向',
  TKeys.tutShadingStep1Instruction: '选定一个光照方向,并在整幅画中保持一致。',
  TKeys.tutShadingStep2Title: '核心阴影',
  TKeys.tutShadingStep2Instruction: '最深的阴影位于明暗交界线之后,而不是形体的最边缘。',

  TKeys.categoriesTitle: '分类',
  TKeys.categoriesSubtitle: '选择一种风格,浏览精选的可供描摹的图片。',
  TKeys.pickImageToTraceArOrPaper: '选择一张图片,用 AR 或在纸上描摹',

  TKeys.settingsTitle: '设置',
  TKeys.sectionDrawing: '绘画',
  TKeys.sectionGeneral: '通用',
  TKeys.sectionAboutSupport: '关于与支持',

  TKeys.pressureSensitivity: '压感灵敏度',
  TKeys.pressureSensitivitySub: '适用于支持压感的触控笔',
  TKeys.leftHandedMode: '左手模式',
  TKeys.leftHandedModeSub: '将工具栏移到左侧',
  TKeys.strokeSmoothing: '笔画平滑',
  TKeys.hapticFeedback: '触感反馈',
  TKeys.autosave: '自动保存',
  TKeys.autosaveSub: '绘画时自动保存更改',
  TKeys.measurementUnit: '测量单位',

  TKeys.moreApps: '更多应用',
  TKeys.shareApp: '分享应用',
  TKeys.privacyPolicy: '隐私政策',
  TKeys.feedback: '反馈',
  TKeys.rateApp: '评价应用',
  TKeys.version: '版本',

  TKeys.choosePhotoToTrace: '选择一张要描摹的照片',
  TKeys.camera: '相机',
  TKeys.opacityLabel: '不透明度',
  TKeys.hideLabel: '隐藏',
  TKeys.extendLabel: '展开',
  TKeys.lockLabel: '锁定',
  TKeys.stepProgress: '步骤:@current/@total',

  TKeys.errNoCameraFound: '此设备未找到摄像头。',
  TKeys.errCameraStartFailed: '无法启动摄像头,请检查权限。',
  TKeys.errFlashToggleFailed: '无法切换闪光灯。',
  TKeys.errFreezeFailed: '无法冻结画面,请重试。',
  TKeys.errImageLoadFailed: '无法加载此图片:@error',
  TKeys.errImageLoadFailedGeneric: '无法加载此图片。',
  TKeys.errImageDisplayFailed: '此图片无法显示,请尝试其他照片。',

  TKeys.nothingToSaveYet: '暂无可保存的内容——这幅速写尚未关联任何项目。',
  TKeys.saved: '已保存',

  TKeys.exportTitle: '导出',
  TKeys.sectionFormat: '格式',
  TKeys.sectionResolution: '分辨率',
  TKeys.flattenLayers: '合并图层',
  TKeys.flattenLayersSub: '将所有可见图层合并为一张图片',
  TKeys.exportedCheck: '已导出 ✓',
  TKeys.exportSketch: '导出速写',
  TKeys.errPermissionDenied: '保存照片的权限被拒绝。',
  TKeys.errPsdComingSoon: 'PSD 导出即将推出。',
  TKeys.errExportFailed: '导出失败:@error',

  TKeys.exportFormatPng: 'PNG',
  TKeys.exportFormatJpg: 'JPG',
  TKeys.exportFormatPdf: 'PDF',
  TKeys.exportFormatPsd: 'PSD(即将推出)',

  TKeys.exportResStandard: '标准 · 1倍',
  TKeys.exportResHigh: '高清 · 2倍',
  TKeys.exportResOriginal: '原始画布尺寸',

  TKeys.layersTitle: '图层',
  TKeys.layerOpacityLabel: '不透明度',
  TKeys.blendModeLabel: '混合模式',
  TKeys.duplicate: '复制',
  TKeys.delete: '删除',

  TKeys.blendNormal: '正常',
  TKeys.blendMultiply: '正片叠底',
  TKeys.blendScreen: '滤色',
  TKeys.blendOverlay: '叠加',
  TKeys.blendDarken: '变暗',
  TKeys.blendLighten: '变亮',

  TKeys.sketchesTitle: '速写',
  TKeys.newSketch: '新建速写',
  TKeys.startYourFirstSketch: '开始你的第一幅速写',
  TKeys.sketchesEmptyDesc: '使用速写工具创作的作品会显示在这里。',

  TKeys.galleryTitle: '相册',
  TKeys.galleryEmptyDesc: '你保存的作品会显示在这里。',

  TKeys.complementaryLabel: '互补色',
  TKeys.colorHistoryLabel: '颜色历史',
  TKeys.hexPrefix: 'HEX #',
  TKeys.noFavoritesYet: '还没有收藏——点击任意颜色上的星标即可收藏。',
  TKeys.noPalettesYet: '还没有调色板',
  TKeys.renamePalette: '重命名调色板',
  TKeys.cancel: '取消',
  TKeys.save: '保存',
  TKeys.newPalette: '新调色板',

  TKeys.toolsTitle: '工具',
  TKeys.sectionUtility: '实用工具',
  TKeys.sectionBrushSettings: '画笔设置',
  TKeys.sizeLabel: '大小',
  TKeys.hardnessLabel: '硬度',

  TKeys.toolPencil: '铅笔',
  TKeys.toolPen: '钢笔',
  TKeys.toolMarker: '马克笔',
  TKeys.toolAirbrush: '喷枪',
  TKeys.toolSmear: '涂抹',
  TKeys.toolEraser: '橡皮擦',
  TKeys.toolFill: '填充',
  TKeys.toolEyedropper: '取色器',
  TKeys.toolShape: '形状',
  TKeys.toolText: '文本',

  TKeys.categoryBasic: '基础',
  TKeys.categoryFineArt: '美术',
  TKeys.categoryMarkers: '马克笔',
  TKeys.categoryArtist: '艺术家',
  TKeys.categoryPastel: '粉彩',
  TKeys.categoryTexture: '纹理',

  TKeys.presetHbPencil: 'HB 铅笔',
  TKeys.presetFineLiner: '细勾线笔',
  TKeys.presetSoftMarker: '软头马克笔',
  TKeys.presetAirbrushSoft: '柔和喷枪',
  TKeys.presetGradePencil: '@grade 铅笔',
  TKeys.presetChiselMarker: '斜头马克笔',
  TKeys.presetBulletMarker: '圆头马克笔',
  TKeys.presetBroadMarker: '宽头马克笔',
  TKeys.presetRoundBrush: '圆头画笔',
  TKeys.presetFlatBrush: '平头画笔',
  TKeys.presetFanBrush: '扇形画笔',
  TKeys.presetSoftPastel: '软粉彩',
  TKeys.presetHardPastel: '硬粉彩',
  TKeys.presetCrosshatch: '交叉排线',
  TKeys.presetGrain: '颗粒',

  TKeys.paletteYellowOrange: '黄色与橙黄色',
  TKeys.paletteWarmOranges: '暖橙色系',
  TKeys.paletteReds: '红色系',
  TKeys.paletteMagenta: '洋红色',
  TKeys.palettePurples: '紫色系',
  TKeys.paletteBlues: '蓝色系',
  TKeys.paletteTeals: '青色系',
  TKeys.paletteGreens: '绿色系',
  TKeys.paletteGreyscale: '灰度',
  TKeys.paletteBrowns: '棕色系',
  TKeys.palettePrimary: '原色',

  TKeys.categoryLegacy: '经典',
  TKeys.categorySynthetic: '合成颜料',
  TKeys.categoryTraditional: '传统',
  TKeys.categoryHalfTone: '半调',
  TKeys.categoryShape: '形状',
  TKeys.categorySplatter: '飞溅',
  TKeys.categoryGlow: '发光',
  TKeys.categorySmudge: '涂抹',
  TKeys.categoryDesigner: '设计师',
  TKeys.categoryColorless: '无色',

  TKeys.errCouldNotLoadImages: '无法加载图片:@error',
  TKeys.noImagesYet: '暂无图片',
  TKeys.addImagesToFolder: '将图片添加到 @folder/,并在 pubspec.yaml 中声明该文件夹。',
  TKeys.howDoYouWantToTraceThis: '你想如何描摹这张图片?',
  TKeys.arCameraOption: 'AR 相机',
  TKeys.arCameraSublabel: '将图片叠加到实时相机画面上',
  TKeys.onPaperOption: '在纸上',
  TKeys.onPaperSublabel: '在屏幕上显示图片,照着画出来',

  TKeys.drawFromCategory: '从@category绘制',
  TKeys.howDoYouWantToTrace2: '你想如何描摹?',
  TKeys.browseCategoryPresets: '进入任一模式后,你可以浏览@category预设。',

  TKeys.rename: '重命名',
  TKeys.exportLabel: '导出',
  TKeys.renameSketch: '重命名速写',
  TKeys.deleteSketchQuestion: '删除速写?',
  TKeys.deleteSketchConfirm: '"@name"将被永久删除。',

  TKeys.catAnime: '动漫',
  TKeys.catCartoon: '卡通',
  TKeys.catPortrait: '人像',
  TKeys.catAnimals: '动物',
  TKeys.catNature: '自然',
  TKeys.catObjects: '物品',

  TKeys.navHome: '首页',
  TKeys.navLearn: '学习',
  TKeys.navCategories: '分类',
  TKeys.navSettings: '设置',

  TKeys.languageSetting: '语言',

  TKeys.preparingYourExperience: '一会儿...',
  TKeys.errCameraPermissionDenied: '相机权限被拒绝',
  TKeys.errGalleryPermissionDenied: '相册权限被拒绝',

  TKeys.notifications: '通知',
  TKeys.notificationsEnabledSub: '您将收到更新和提醒。',
  TKeys.notificationsDisabledSub: '轻点以在系统设置中启用',
};